# Data Preprocessing 

In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from sklearn.preprocessing import OneHotEncoder

from fastai.imports import *
from fastai.tabular.all import *

from numpy import random
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
from sklearn import metrics
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

import eli5
from eli5.sklearn import PermutationImportance


from scipy.stats import skew, norm
from catboost import CatBoostRegressor
from feature_engine.transformation import YeoJohnsonTransformer
from category_encoders.binary import BinaryEncoder

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
import shap
import xgboost
from sklearn.svm import SVR
from lightgbm import LGBMRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeRegressor
from mlxtend.regressor import StackingRegressor
from sklearn.linear_model import LinearRegression, BayesianRidge
from sklearn.model_selection import RepeatedKFold
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import VotingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.preprocessing import RobustScaler
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.decomposition import PCA
from mlxtend.regressor import StackingCVRegressor

In [3]:
test = pd.read_csv('test.csv')
sample = pd.read_csv('sample_submission.csv')
train = pd.read_csv('train.csv')

In [4]:
train.shape, test.shape

((1460, 81), (1459, 80))

Based on an initial analysis the train and test datasets have similar characteristics, so it will be easier to combine them for the data preprocessing work. 

In [5]:
train_test = pd.concat([train, test], ignore_index=True)

In [6]:
train_test.shape

(2919, 81)

To show the amount of 'NaN' values in each column of the dataset. 

In [7]:
pd.isnull(train_test).sum()[pd.isnull(train_test).sum() > 0]

MSZoning           4
LotFrontage      486
Alley           2721
Utilities          2
Exterior1st        1
Exterior2nd        1
MasVnrType        24
MasVnrArea        23
BsmtQual          81
BsmtCond          82
BsmtExposure      82
BsmtFinType1      79
BsmtFinSF1         1
BsmtFinType2      80
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
Electrical         1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
FireplaceQu     1420
GarageType       157
GarageYrBlt      159
GarageFinish     159
GarageCars         1
GarageArea         1
GarageQual       159
GarageCond       159
PoolQC          2909
Fence           2348
MiscFeature     2814
SaleType           1
SalePrice       1459
dtype: int64

It looks like Alley, FireplaceQu, PoolQC, Fence and MiscFeature have significant numbers of missing data. At first those columns were eliminated. However, the results were better if these columns were retained and the missing data were coded as 'None', assuming these features didn't exist for their related houses. 

There are a number of rows that have less than 5 rows with missing data. Since some of these are categorical and some are continuous data, their missing data will be replaced with the most frequent value. 

In [8]:
drop_high_nan=['Alley','FireplaceQu','PoolQC','Fence','MiscFeature']
train_test[drop_high_nan] = train_test[drop_high_nan].fillna('None')

small_nan_cols = ['MSZoning', 'Utilities', 'Exterior1st', 'Exterior2nd', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 
                  'TotalBsmtSF', 'Electrical', 'BsmtFullBath', 'BsmtHalfBath', 'KitchenQual', 'Functional', 'GarageCars', 
                  'GarageArea','SaleType', 'SaleCondition']
small_impute = SimpleImputer(strategy='most_frequent')
train_test[small_nan_cols] = pd.DataFrame(small_impute.fit_transform(train_test[small_nan_cols]),columns=small_nan_cols)

The following columns seem to have one value significantly larger than the rest, and it would probably be best to use the mode, or most common, value to feel each NaN value: MasVnrType, MasVnrArea, BsmtCond, BsmtExposure, BsmtFinType2, GarageType, GarageFinish, GarageQual, and GarageCond. That represents 9 out of the 13 columns. 

BsmtQual has two values larger than the rest: Gd and TA. But it only has 2.8% NaNs, so simply using the mode might be good enough.  

GarageYrBlt has 59 NaNs out 2919 rows which is only 2%. It has a dispersed set of values, so it might be easiest just to have any NaNs have the same value as YearBuilt. 

BsmtFinType1 has only 2.7% value of NaNs, and most two of its largest values are GLQ and Unf. It might be easiest to use the mode here. 

LotFrontage has 486 NaNs out of 2919 rows which is a pretty high 16.7%. It has a dispersed range of values, but looking at its characteristics from the describe function above, it seems to have a pretty even distribution with a mean of 10,168 and a median of 9,453. So using the mean to fill in the NaNs seems reasonable.

In [9]:
mode_cols = ['MasVnrType', 'MasVnrArea', 'BsmtCond', 'BsmtExposure', 'BsmtFinType2', 'BsmtQual', 'BsmtFinType1']
mode_impute = SimpleImputer(strategy='most_frequent')
train_test[mode_cols] = pd.DataFrame(mode_impute.fit_transform(train_test[mode_cols]),columns=mode_cols)

garage_cols = ['GarageType', 'GarageFinish', 'GarageQual','GarageCond', 'GarageYrBlt']
train_test[garage_cols] = train_test[garage_cols].fillna('None')

train_test['LotFrontage'].fillna((train_test['LotFrontage'].mean()), inplace=True)

A final check to ensure that the only missing values are the expected SalePrice data from the test dataset. 

In [10]:
pd.isnull(train_test).sum()[pd.isnull(train_test).sum() > 0]

SalePrice    1459
dtype: int64

The BsmtQual and BsmtFinType1 have ordinal scaled categorical values with an inherent order. So the conversion from categorical to numerical was done manually. 

In [11]:
train_test['BsmtQual'].unique()

array(['Gd', 'TA', 'Ex', 'Fa'], dtype=object)

In [12]:
train_test['BsmtFinType1'].unique()

array(['GLQ', 'ALQ', 'Unf', 'Rec', 'BLQ', 'LwQ'], dtype=object)

In [13]:
train_test.BsmtQual = train_test.BsmtQual.replace({"Ex": 110, "Gd": 95, "TA": 85, "Fa": 75, "Po": 60, "NA": 0})
train_test.BsmtFinType1 = train_test.BsmtFinType1.replace({"GLQ": 6, "ALQ": 5, "BLQ": 4, "Rec": 3, "LwQ": 2, "Unf": 1,
                                                         "NA": 0})

To look at how many features have a skew above 0.6, since high skew can be an issue in regression analysis. For some reason, the results were better with a skew limit of 0.6 than the more standard value of 0.5. Skewness measures how symmetrical a distribution of data is. Data with a skew of 0 is perfectly symmetrical.

In [14]:
number_cols = train_test.select_dtypes(include=np.number).columns.tolist()

In [15]:
skew_features = train_test[number_cols].apply(lambda x: skew(x)).sort_values(ascending=False)
high_skew = skew_features[skew_features > 0.6]
skew_index = high_skew.index
skew_index

Index(['MiscVal', 'PoolArea', 'LotArea', 'LowQualFinSF', '3SsnPorch',
       'KitchenAbvGr', 'EnclosedPorch', 'ScreenPorch', 'OpenPorchSF',
       'WoodDeckSF', 'LotFrontage', '1stFlrSF', 'MSSubClass', 'GrLivArea',
       '2ndFlrSF', 'BsmtQual', 'TotRmsAbvGrd', 'Fireplaces', 'HalfBath'],
      dtype='object')

In [16]:
print("There are {} numerical features with Skew > 0.6 :".format(high_skew.shape[0]))
skewness = pd.DataFrame({'Skew' :high_skew})
skewness

There are 19 numerical features with Skew > 0.6 :


Skew
MiscVal        21.947195
PoolArea       16.898328
LotArea        12.822431
LowQualFinSF   12.088761
3SsnPorch      11.376065
KitchenAbvGr    4.302254
EnclosedPorch   4.003891
ScreenPorch     3.946694
OpenPorchSF     2.535114
WoodDeckSF      1.842433
LotFrontage     1.645574
1stFlrSF        1.469604
MSSubClass      1.375457
GrLivArea       1.269358
2ndFlrSF        0.861675
BsmtQual        0.796302
TotRmsAbvGrd    0.758367
Fireplaces      0.733495
HalfBath        0.694566

To normalize the features with skew above 0.6 the Yeo-Johnson Transformation is used since data with negative values or values of zero can be included. This transformation is a way to transform a continuous variable so that the output looks more normally distributed. 

In [17]:
yjt = YeoJohnsonTransformer()
yjt.fit(train_test[skew_index])
train_test[skew_index] = yjt.transform(train_test[skew_index])

Since most models cannot work with categorical data, it will be necessary to identify all the columns that have non-numeric object values and then convert them to numeric values. The best approach for this conversion seems to be the straightforward python factorize function. 

In [18]:
obj_cols = list(train_test.select_dtypes(['object']).columns)

In [19]:
for column in obj_cols:
     train_test[column] = pd.factorize(train_test[column], sort=True)[0]

To create some new columns that might compound the effects of the existing columns with higher impact on using the xgbregressor model. This work was done on an earlier workbook version. The get_score function with 'gain' as the importance type was used. This function takes the average gain of the tree splits. 

In [20]:
train_test['QualCondSum'] = train_test['OverallQual'] + train_test['OverallCond']
train_test['RemodTime'] = train_test['YearRemodAdd'] - train_test['YearBuilt']
train_test['BsmtFinTypeSF1'] = train_test['BsmtFinType1'] * train_test['BsmtFinSF1']
train_test['TotalFlrSF'] = train_test['1stFlrSF'] + train_test['2ndFlrSF']
train_test['TotalFinSF'] = train_test['GrLivArea'] + train_test['BsmtFinSF1']
train_test['GarageCarArea'] = train_test['GarageArea'] * train_test['GarageCars']
train_test['TotalSF'] = train_test['1stFlrSF'] + train_test['2ndFlrSF'] + train_test['TotalBsmtSF']

To create a column with the log of the SalePrice to match the evaluation metric in the contest. 

In [21]:
train_test['LogSalePrice'] = train_test['SalePrice'].apply(np.log)

#  Setting Up and Running the Models

To separate the train_test dataset back into the train and test datasets and identify the independent and dependent columns. Because the dataset is so small, the cross fold validation process seemed to have much less overfitting than creating the separate validation and training sets. 

In [22]:
train = train_test[train_test['SalePrice'].notnull()].copy()
test = train_test[train_test['SalePrice'].isnull()].drop(['SalePrice','LogSalePrice'],axis=1)
X = train.drop(['SalePrice','LogSalePrice'],axis=1)
y = train.LogSalePrice

In [23]:
X,y = shuffle(X,y, random_state=42)
X = X.reset_index(drop=True)
y = y.reset_index(drop=True)

To set up the cross validation folds.

In [24]:
kf = KFold(n_splits=12, random_state=42, shuffle=True)

In a separate workbook, Optuna was used to find the optimal parameters for a wide selection of regression models. It was interesting that the results using Optuna were not significantly better than using the default parameters for most of the models. 

In [25]:
cat_model = CatBoostRegressor(colsample_bylevel= 0.08309602563537534, learning_rate= 0.08286145675756133, depth= 4, 
                              l2_leaf_reg= 14.555249413444315, subsample= 0.9097411584295835, 
                              bagging_temperature= 3.177590955252409, model_size_reg= 0.3808343022980778, 
                              boosting_type= 'Plain')

xgb_model = xgb.XGBRegressor(reg_lambda= 5.096430599223015, alpha= 1.3223698329753615, 
                             colsample_bytree= 0.10366646849522436, subsample= 0.9705075073357825, 
                             learning_rate= 0.04681670801808327, n_estimators= 2340, max_depth= 3, 
                             min_child_weight= 2, num_parallel_tree= 1,
                             objective= 'reg:linear', random_state=42)

lr_model = LinearRegression()

br_model = BayesianRidge(alpha_init= 1.4228919418021304, lambda_init= 0.03899454131279402, compute_score=True)

lightgbm_model = LGBMRegressor(objective='regression', 
                       num_leaves=9,
                       learning_rate=0.0019200325083996161, 
                       n_estimators=7000,
                       max_bin=200, 
                       subsample= 0.40495582495561083, 
                       bagging_fraction=0.4240987934393466,
                       bagging_freq=4, 
                       bagging_seed=8,
                       feature_fraction=0.1309662269268009,
                       feature_fraction_seed=8,
                       min_sum_hessian_in_leaf = 1,
                       verbose=-1,
                       random_state=42)

svr_model = make_pipeline(RobustScaler(), SVR(C=29.994348636600485, epsilon= 0.019482341995527, 
                                              gamma=0.0009992835981754227))

dtr_model = DecisionTreeRegressor()

rfr_model = RandomForestRegressor(n_estimators=1200,
                          max_depth=10,
                          min_weight_fraction_leaf=0,
                          min_samples_split=5,
                          min_samples_leaf=1,
                          max_leaf_nodes=90,
                          max_features=None,
                          oob_score=True,
                          random_state=42)

gbr_model = GradientBoostingRegressor(n_estimators=2200,
                                learning_rate=0.05005099614548874,
                                max_depth=2,
                                max_features='sqrt',
                                min_samples_leaf=3,
                                min_samples_split=24,
                                loss='huber',
                                random_state=42)

ridge_alphas = [1e-15, 1e-10, 1e-8, 9e-4, 7e-4, 5e-4, 3e-4, 1e-4, 1e-3, 5e-2, 1e-2, 0.1, 0.3, 1, 3, 5, 10, 15, 
                18, 20, 30, 50, 75, 100]
ridge_model = make_pipeline(RobustScaler(), RidgeCV(alphas=ridge_alphas, cv=kf))

To define the scoring metric. 

In [26]:
def rmse_cv(model,X,y):
    rmse = np.sqrt(-cross_val_score(model, X, y, scoring="neg_mean_squared_error", cv=kf))
    return rmse

To define the model names and models and then create a loop to run each model and print out their scores. 

In [27]:
model_names = ['CatBoostRegressor','XGBRegressor','LinearRegression','BayesianRidge','LGBMRegressor',
               'SVR','DecisionTreeRegressor','RandomForestRegressor','GradientBoostingRegressor','RidgeRegressor']

In [28]:
models = [cat_model,xgb_model,lr_model,br_model,lightgbm_model,svr_model,dtr_model,rfr_model,gbr_model,ridge_model]

In [29]:
score_rmse = []
for i in models:
    rmse = np.sqrt(-cross_val_score(i, X, y, scoring="neg_mean_squared_error", cv=kf))
    ave_rmse = np.mean(rmse)
    score_rmse.append(ave_rmse)

0:	learn: 0.3844132	total: 139ms	remaining: 2m 18s
1:	learn: 0.3675341	total: 140ms	remaining: 1m 10s
2:	learn: 0.3525793	total: 142ms	remaining: 47.1s
3:	learn: 0.3386058	total: 143ms	remaining: 35.5s
4:	learn: 0.3275463	total: 144ms	remaining: 28.6s
5:	learn: 0.3147258	total: 145ms	remaining: 24s
6:	learn: 0.3052153	total: 146ms	remaining: 20.7s
7:	learn: 0.2947593	total: 147ms	remaining: 18.3s
8:	learn: 0.2836075	total: 148ms	remaining: 16.3s
9:	learn: 0.2738717	total: 150ms	remaining: 14.8s
10:	learn: 0.2656770	total: 151ms	remaining: 13.6s
11:	learn: 0.2574640	total: 152ms	remaining: 12.5s
12:	learn: 0.2500886	total: 153ms	remaining: 11.6s
13:	learn: 0.2428996	total: 154ms	remaining: 10.9s
14:	learn: 0.2360489	total: 155ms	remaining: 10.2s
15:	learn: 0.2297101	total: 157ms	remaining: 9.63s
16:	learn: 0.2256423	total: 158ms	remaining: 9.12s
17:	learn: 0.2204713	total: 159ms	remaining: 8.68s
18:	learn: 0.2158843	total: 160ms	remaining: 8.28s
19:	learn: 0.2115626	total: 161ms	remaini

176:	learn: 0.1107047	total: 334ms	remaining: 1.55s
177:	learn: 0.1106375	total: 335ms	remaining: 1.54s
178:	learn: 0.1105841	total: 336ms	remaining: 1.54s
179:	learn: 0.1103979	total: 337ms	remaining: 1.53s
180:	learn: 0.1103214	total: 338ms	remaining: 1.53s
181:	learn: 0.1103051	total: 339ms	remaining: 1.52s
182:	learn: 0.1102087	total: 340ms	remaining: 1.52s
183:	learn: 0.1100213	total: 341ms	remaining: 1.51s
184:	learn: 0.1099309	total: 342ms	remaining: 1.51s
185:	learn: 0.1096876	total: 343ms	remaining: 1.5s
186:	learn: 0.1096614	total: 344ms	remaining: 1.5s
187:	learn: 0.1096100	total: 346ms	remaining: 1.49s
188:	learn: 0.1094205	total: 347ms	remaining: 1.49s
189:	learn: 0.1092712	total: 348ms	remaining: 1.48s
190:	learn: 0.1090777	total: 349ms	remaining: 1.48s
191:	learn: 0.1089382	total: 350ms	remaining: 1.47s
192:	learn: 0.1088492	total: 351ms	remaining: 1.47s
193:	learn: 0.1087998	total: 352ms	remaining: 1.46s
194:	learn: 0.1087126	total: 353ms	remaining: 1.46s
195:	learn: 0.

347:	learn: 0.0942088	total: 521ms	remaining: 977ms
348:	learn: 0.0941890	total: 522ms	remaining: 974ms
349:	learn: 0.0941824	total: 523ms	remaining: 972ms
350:	learn: 0.0941685	total: 524ms	remaining: 970ms
351:	learn: 0.0939562	total: 526ms	remaining: 968ms
352:	learn: 0.0938056	total: 527ms	remaining: 965ms
353:	learn: 0.0937071	total: 528ms	remaining: 963ms
354:	learn: 0.0936657	total: 529ms	remaining: 960ms
355:	learn: 0.0935730	total: 530ms	remaining: 958ms
356:	learn: 0.0934691	total: 531ms	remaining: 956ms
357:	learn: 0.0934172	total: 532ms	remaining: 953ms
358:	learn: 0.0933508	total: 533ms	remaining: 951ms
359:	learn: 0.0933237	total: 534ms	remaining: 949ms
360:	learn: 0.0933021	total: 535ms	remaining: 946ms
361:	learn: 0.0932866	total: 536ms	remaining: 944ms
362:	learn: 0.0932016	total: 537ms	remaining: 943ms
363:	learn: 0.0931563	total: 538ms	remaining: 940ms
364:	learn: 0.0930199	total: 539ms	remaining: 938ms
365:	learn: 0.0928418	total: 541ms	remaining: 936ms
366:	learn: 

523:	learn: 0.0827826	total: 705ms	remaining: 641ms
524:	learn: 0.0827653	total: 706ms	remaining: 639ms
525:	learn: 0.0826969	total: 707ms	remaining: 637ms
526:	learn: 0.0826414	total: 709ms	remaining: 636ms
527:	learn: 0.0825301	total: 710ms	remaining: 635ms
528:	learn: 0.0825247	total: 711ms	remaining: 633ms
529:	learn: 0.0825056	total: 712ms	remaining: 631ms
530:	learn: 0.0824670	total: 713ms	remaining: 629ms
531:	learn: 0.0823750	total: 714ms	remaining: 628ms
532:	learn: 0.0823695	total: 715ms	remaining: 626ms
533:	learn: 0.0823378	total: 716ms	remaining: 625ms
534:	learn: 0.0823282	total: 717ms	remaining: 623ms
535:	learn: 0.0823246	total: 718ms	remaining: 621ms
536:	learn: 0.0823223	total: 718ms	remaining: 619ms
537:	learn: 0.0823153	total: 720ms	remaining: 618ms
538:	learn: 0.0822419	total: 721ms	remaining: 616ms
539:	learn: 0.0822358	total: 722ms	remaining: 615ms
540:	learn: 0.0822150	total: 723ms	remaining: 613ms
541:	learn: 0.0821315	total: 724ms	remaining: 611ms
542:	learn: 

703:	learn: 0.0742842	total: 892ms	remaining: 375ms
704:	learn: 0.0742313	total: 893ms	remaining: 374ms
705:	learn: 0.0741562	total: 895ms	remaining: 373ms
706:	learn: 0.0741402	total: 896ms	remaining: 371ms
707:	learn: 0.0741108	total: 897ms	remaining: 370ms
708:	learn: 0.0740515	total: 899ms	remaining: 369ms
709:	learn: 0.0740312	total: 900ms	remaining: 368ms
710:	learn: 0.0739901	total: 901ms	remaining: 366ms
711:	learn: 0.0739792	total: 902ms	remaining: 365ms
712:	learn: 0.0739711	total: 903ms	remaining: 364ms
713:	learn: 0.0739339	total: 904ms	remaining: 362ms
714:	learn: 0.0739022	total: 905ms	remaining: 361ms
715:	learn: 0.0738950	total: 906ms	remaining: 359ms
716:	learn: 0.0738239	total: 907ms	remaining: 358ms
717:	learn: 0.0738171	total: 909ms	remaining: 357ms
718:	learn: 0.0737718	total: 910ms	remaining: 356ms
719:	learn: 0.0737656	total: 919ms	remaining: 358ms
720:	learn: 0.0736739	total: 921ms	remaining: 356ms
721:	learn: 0.0736694	total: 923ms	remaining: 355ms
722:	learn: 

0:	learn: 0.3846661	total: 1.42ms	remaining: 1.42s
1:	learn: 0.3675019	total: 2.83ms	remaining: 1.41s
2:	learn: 0.3508888	total: 4.07ms	remaining: 1.35s
3:	learn: 0.3369057	total: 5.69ms	remaining: 1.42s
4:	learn: 0.3259866	total: 6.88ms	remaining: 1.37s
5:	learn: 0.3126201	total: 8.04ms	remaining: 1.33s
6:	learn: 0.3028940	total: 9.44ms	remaining: 1.34s
7:	learn: 0.2930903	total: 10.5ms	remaining: 1.3s
8:	learn: 0.2825992	total: 11.6ms	remaining: 1.27s
9:	learn: 0.2728510	total: 12.6ms	remaining: 1.25s
10:	learn: 0.2647144	total: 13.7ms	remaining: 1.23s
11:	learn: 0.2564391	total: 14.7ms	remaining: 1.21s
12:	learn: 0.2490763	total: 15.7ms	remaining: 1.2s
13:	learn: 0.2419568	total: 16.7ms	remaining: 1.18s
14:	learn: 0.2352283	total: 17.7ms	remaining: 1.17s
15:	learn: 0.2291928	total: 18.9ms	remaining: 1.16s
16:	learn: 0.2250715	total: 20.2ms	remaining: 1.17s
17:	learn: 0.2200158	total: 21.5ms	remaining: 1.17s
18:	learn: 0.2153777	total: 22.6ms	remaining: 1.17s
19:	learn: 0.2115341	tot

160:	learn: 0.1126315	total: 190ms	remaining: 992ms
161:	learn: 0.1125644	total: 192ms	remaining: 992ms
162:	learn: 0.1125416	total: 193ms	remaining: 992ms
163:	learn: 0.1123736	total: 195ms	remaining: 993ms
164:	learn: 0.1121753	total: 196ms	remaining: 993ms
165:	learn: 0.1119295	total: 198ms	remaining: 994ms
166:	learn: 0.1117118	total: 199ms	remaining: 995ms
167:	learn: 0.1114955	total: 201ms	remaining: 996ms
168:	learn: 0.1114481	total: 202ms	remaining: 996ms
169:	learn: 0.1112181	total: 205ms	remaining: 999ms
170:	learn: 0.1111808	total: 206ms	remaining: 1s
171:	learn: 0.1108725	total: 208ms	remaining: 1s
172:	learn: 0.1108350	total: 210ms	remaining: 1s
173:	learn: 0.1107744	total: 211ms	remaining: 1s
174:	learn: 0.1107137	total: 213ms	remaining: 1s
175:	learn: 0.1106465	total: 215ms	remaining: 1.01s
176:	learn: 0.1105234	total: 217ms	remaining: 1.01s
177:	learn: 0.1104979	total: 219ms	remaining: 1.01s
178:	learn: 0.1104443	total: 221ms	remaining: 1.01s
179:	learn: 0.1102658	total

434:	learn: 0.0868335	total: 557ms	remaining: 723ms
435:	learn: 0.0867729	total: 558ms	remaining: 722ms
436:	learn: 0.0866914	total: 560ms	remaining: 721ms
437:	learn: 0.0865959	total: 561ms	remaining: 720ms
438:	learn: 0.0865838	total: 562ms	remaining: 718ms
439:	learn: 0.0865004	total: 563ms	remaining: 717ms
440:	learn: 0.0864249	total: 565ms	remaining: 716ms
441:	learn: 0.0863299	total: 566ms	remaining: 714ms
442:	learn: 0.0863265	total: 567ms	remaining: 713ms
443:	learn: 0.0862726	total: 568ms	remaining: 711ms
444:	learn: 0.0861362	total: 569ms	remaining: 710ms
445:	learn: 0.0860269	total: 570ms	remaining: 708ms
446:	learn: 0.0860071	total: 571ms	remaining: 707ms
447:	learn: 0.0859923	total: 572ms	remaining: 705ms
448:	learn: 0.0858762	total: 573ms	remaining: 703ms
449:	learn: 0.0858573	total: 574ms	remaining: 702ms
450:	learn: 0.0858066	total: 576ms	remaining: 701ms
451:	learn: 0.0858025	total: 577ms	remaining: 699ms
452:	learn: 0.0856433	total: 578ms	remaining: 698ms
453:	learn: 

593:	learn: 0.0778882	total: 752ms	remaining: 514ms
594:	learn: 0.0778685	total: 754ms	remaining: 513ms
595:	learn: 0.0777749	total: 756ms	remaining: 512ms
596:	learn: 0.0776847	total: 757ms	remaining: 511ms
597:	learn: 0.0776224	total: 759ms	remaining: 510ms
598:	learn: 0.0776132	total: 760ms	remaining: 509ms
599:	learn: 0.0774955	total: 761ms	remaining: 508ms
600:	learn: 0.0774663	total: 763ms	remaining: 506ms
601:	learn: 0.0773763	total: 764ms	remaining: 505ms
602:	learn: 0.0773629	total: 765ms	remaining: 504ms
603:	learn: 0.0772806	total: 766ms	remaining: 503ms
604:	learn: 0.0772525	total: 768ms	remaining: 501ms
605:	learn: 0.0771717	total: 769ms	remaining: 500ms
606:	learn: 0.0771528	total: 770ms	remaining: 499ms
607:	learn: 0.0770793	total: 772ms	remaining: 498ms
608:	learn: 0.0769997	total: 774ms	remaining: 497ms
609:	learn: 0.0769596	total: 775ms	remaining: 495ms
610:	learn: 0.0768881	total: 776ms	remaining: 494ms
611:	learn: 0.0768805	total: 777ms	remaining: 493ms
612:	learn: 

903:	learn: 0.0651451	total: 1.13s	remaining: 120ms
904:	learn: 0.0651263	total: 1.13s	remaining: 119ms
905:	learn: 0.0650984	total: 1.13s	remaining: 117ms
906:	learn: 0.0650724	total: 1.13s	remaining: 116ms
907:	learn: 0.0650162	total: 1.13s	remaining: 115ms
908:	learn: 0.0649903	total: 1.14s	remaining: 114ms
909:	learn: 0.0649131	total: 1.14s	remaining: 112ms
910:	learn: 0.0648992	total: 1.14s	remaining: 111ms
911:	learn: 0.0648104	total: 1.14s	remaining: 110ms
912:	learn: 0.0647502	total: 1.14s	remaining: 109ms
913:	learn: 0.0646605	total: 1.14s	remaining: 107ms
914:	learn: 0.0646154	total: 1.14s	remaining: 106ms
915:	learn: 0.0645589	total: 1.14s	remaining: 105ms
916:	learn: 0.0645375	total: 1.15s	remaining: 104ms
917:	learn: 0.0644505	total: 1.15s	remaining: 102ms
918:	learn: 0.0644477	total: 1.15s	remaining: 101ms
919:	learn: 0.0644424	total: 1.15s	remaining: 99.9ms
920:	learn: 0.0644277	total: 1.15s	remaining: 98.6ms
921:	learn: 0.0644255	total: 1.15s	remaining: 97.4ms
922:	lear

183:	learn: 0.1093780	total: 215ms	remaining: 955ms
184:	learn: 0.1093204	total: 216ms	remaining: 953ms
185:	learn: 0.1090445	total: 218ms	remaining: 952ms
186:	learn: 0.1090092	total: 219ms	remaining: 951ms
187:	learn: 0.1089506	total: 220ms	remaining: 949ms
188:	learn: 0.1087956	total: 221ms	remaining: 948ms
189:	learn: 0.1087494	total: 222ms	remaining: 946ms
190:	learn: 0.1084770	total: 223ms	remaining: 944ms
191:	learn: 0.1082956	total: 224ms	remaining: 944ms
192:	learn: 0.1081937	total: 225ms	remaining: 942ms
193:	learn: 0.1081482	total: 226ms	remaining: 941ms
194:	learn: 0.1080908	total: 228ms	remaining: 940ms
195:	learn: 0.1080213	total: 229ms	remaining: 939ms
196:	learn: 0.1078948	total: 230ms	remaining: 938ms
197:	learn: 0.1077425	total: 232ms	remaining: 938ms
198:	learn: 0.1077263	total: 233ms	remaining: 940ms
199:	learn: 0.1076680	total: 236ms	remaining: 943ms
200:	learn: 0.1075365	total: 237ms	remaining: 944ms
201:	learn: 0.1074036	total: 239ms	remaining: 944ms
202:	learn: 

469:	learn: 0.0847462	total: 580ms	remaining: 653ms
470:	learn: 0.0847277	total: 581ms	remaining: 652ms
471:	learn: 0.0845764	total: 582ms	remaining: 651ms
472:	learn: 0.0845720	total: 583ms	remaining: 650ms
473:	learn: 0.0845645	total: 584ms	remaining: 648ms
474:	learn: 0.0845263	total: 585ms	remaining: 647ms
475:	learn: 0.0844719	total: 586ms	remaining: 646ms
476:	learn: 0.0844676	total: 587ms	remaining: 644ms
477:	learn: 0.0844578	total: 589ms	remaining: 643ms
478:	learn: 0.0844309	total: 590ms	remaining: 641ms
479:	learn: 0.0843598	total: 591ms	remaining: 640ms
480:	learn: 0.0842243	total: 592ms	remaining: 639ms
481:	learn: 0.0842164	total: 593ms	remaining: 637ms
482:	learn: 0.0842137	total: 594ms	remaining: 636ms
483:	learn: 0.0841267	total: 595ms	remaining: 635ms
484:	learn: 0.0840558	total: 596ms	remaining: 633ms
485:	learn: 0.0840520	total: 597ms	remaining: 632ms
486:	learn: 0.0839503	total: 599ms	remaining: 631ms
487:	learn: 0.0839301	total: 600ms	remaining: 630ms
488:	learn: 

634:	learn: 0.0767912	total: 762ms	remaining: 438ms
635:	learn: 0.0767366	total: 763ms	remaining: 437ms
636:	learn: 0.0767231	total: 764ms	remaining: 436ms
637:	learn: 0.0766829	total: 766ms	remaining: 434ms
638:	learn: 0.0766048	total: 767ms	remaining: 433ms
639:	learn: 0.0766000	total: 768ms	remaining: 432ms
640:	learn: 0.0765672	total: 769ms	remaining: 431ms
641:	learn: 0.0765304	total: 770ms	remaining: 429ms
642:	learn: 0.0764223	total: 771ms	remaining: 428ms
643:	learn: 0.0763324	total: 773ms	remaining: 427ms
644:	learn: 0.0763237	total: 774ms	remaining: 426ms
645:	learn: 0.0763090	total: 775ms	remaining: 425ms
646:	learn: 0.0762429	total: 776ms	remaining: 423ms
647:	learn: 0.0762391	total: 777ms	remaining: 422ms
648:	learn: 0.0761996	total: 778ms	remaining: 421ms
649:	learn: 0.0761106	total: 780ms	remaining: 420ms
650:	learn: 0.0761036	total: 781ms	remaining: 419ms
651:	learn: 0.0760826	total: 782ms	remaining: 417ms
652:	learn: 0.0760496	total: 783ms	remaining: 416ms
653:	learn: 

954:	learn: 0.0653169	total: 1.14s	remaining: 53.8ms
955:	learn: 0.0653127	total: 1.14s	remaining: 52.6ms
956:	learn: 0.0653055	total: 1.14s	remaining: 51.4ms
957:	learn: 0.0652730	total: 1.14s	remaining: 50.2ms
958:	learn: 0.0652306	total: 1.15s	remaining: 49ms
959:	learn: 0.0652191	total: 1.15s	remaining: 47.8ms
960:	learn: 0.0651666	total: 1.15s	remaining: 46.6ms
961:	learn: 0.0651639	total: 1.15s	remaining: 45.4ms
962:	learn: 0.0651226	total: 1.15s	remaining: 44.2ms
963:	learn: 0.0650553	total: 1.15s	remaining: 43ms
964:	learn: 0.0650458	total: 1.15s	remaining: 41.8ms
965:	learn: 0.0650058	total: 1.15s	remaining: 40.6ms
966:	learn: 0.0649903	total: 1.16s	remaining: 39.5ms
967:	learn: 0.0649447	total: 1.16s	remaining: 38.3ms
968:	learn: 0.0648672	total: 1.16s	remaining: 37.1ms
969:	learn: 0.0648631	total: 1.16s	remaining: 35.9ms
970:	learn: 0.0648296	total: 1.16s	remaining: 34.7ms
971:	learn: 0.0648064	total: 1.16s	remaining: 33.5ms
972:	learn: 0.0647908	total: 1.16s	remaining: 32.3

174:	learn: 0.1108561	total: 251ms	remaining: 1.18s
175:	learn: 0.1108007	total: 253ms	remaining: 1.18s
176:	learn: 0.1106615	total: 254ms	remaining: 1.18s
177:	learn: 0.1105753	total: 255ms	remaining: 1.18s
178:	learn: 0.1105172	total: 256ms	remaining: 1.17s
179:	learn: 0.1103082	total: 257ms	remaining: 1.17s
180:	learn: 0.1102438	total: 259ms	remaining: 1.17s
181:	learn: 0.1100789	total: 260ms	remaining: 1.17s
182:	learn: 0.1099048	total: 261ms	remaining: 1.16s
183:	learn: 0.1097311	total: 262ms	remaining: 1.16s
184:	learn: 0.1096411	total: 263ms	remaining: 1.16s
185:	learn: 0.1093911	total: 264ms	remaining: 1.16s
186:	learn: 0.1093565	total: 266ms	remaining: 1.15s
187:	learn: 0.1093021	total: 267ms	remaining: 1.15s
188:	learn: 0.1091055	total: 268ms	remaining: 1.15s
189:	learn: 0.1090704	total: 269ms	remaining: 1.15s
190:	learn: 0.1087517	total: 271ms	remaining: 1.15s
191:	learn: 0.1087330	total: 272ms	remaining: 1.14s
192:	learn: 0.1086530	total: 273ms	remaining: 1.14s
193:	learn: 

335:	learn: 0.0950112	total: 434ms	remaining: 858ms
336:	learn: 0.0949458	total: 436ms	remaining: 857ms
337:	learn: 0.0948616	total: 437ms	remaining: 855ms
338:	learn: 0.0947470	total: 438ms	remaining: 855ms
339:	learn: 0.0945153	total: 439ms	remaining: 853ms
340:	learn: 0.0944564	total: 441ms	remaining: 852ms
341:	learn: 0.0944512	total: 442ms	remaining: 850ms
342:	learn: 0.0944305	total: 443ms	remaining: 848ms
343:	learn: 0.0943649	total: 444ms	remaining: 847ms
344:	learn: 0.0943104	total: 445ms	remaining: 845ms
345:	learn: 0.0941898	total: 446ms	remaining: 843ms
346:	learn: 0.0940433	total: 447ms	remaining: 842ms
347:	learn: 0.0939086	total: 449ms	remaining: 840ms
348:	learn: 0.0938887	total: 450ms	remaining: 839ms
349:	learn: 0.0938837	total: 451ms	remaining: 838ms
350:	learn: 0.0938700	total: 452ms	remaining: 836ms
351:	learn: 0.0936472	total: 453ms	remaining: 835ms
352:	learn: 0.0934378	total: 454ms	remaining: 833ms
353:	learn: 0.0933137	total: 455ms	remaining: 831ms
354:	learn: 

500:	learn: 0.0827047	total: 621ms	remaining: 619ms
501:	learn: 0.0826788	total: 623ms	remaining: 618ms
502:	learn: 0.0826419	total: 624ms	remaining: 617ms
503:	learn: 0.0826383	total: 625ms	remaining: 615ms
504:	learn: 0.0826326	total: 626ms	remaining: 614ms
505:	learn: 0.0825396	total: 627ms	remaining: 612ms
506:	learn: 0.0825313	total: 628ms	remaining: 611ms
507:	learn: 0.0825131	total: 629ms	remaining: 609ms
508:	learn: 0.0824014	total: 631ms	remaining: 608ms
509:	learn: 0.0823440	total: 632ms	remaining: 607ms
510:	learn: 0.0823302	total: 633ms	remaining: 606ms
511:	learn: 0.0823259	total: 634ms	remaining: 604ms
512:	learn: 0.0822768	total: 635ms	remaining: 603ms
513:	learn: 0.0822011	total: 636ms	remaining: 602ms
514:	learn: 0.0821863	total: 638ms	remaining: 601ms
515:	learn: 0.0821755	total: 639ms	remaining: 599ms
516:	learn: 0.0820883	total: 640ms	remaining: 598ms
517:	learn: 0.0820075	total: 641ms	remaining: 597ms
518:	learn: 0.0819809	total: 642ms	remaining: 595ms
519:	learn: 

667:	learn: 0.0752185	total: 808ms	remaining: 402ms
668:	learn: 0.0752107	total: 809ms	remaining: 400ms
669:	learn: 0.0751568	total: 811ms	remaining: 399ms
670:	learn: 0.0751374	total: 812ms	remaining: 398ms
671:	learn: 0.0751294	total: 813ms	remaining: 397ms
672:	learn: 0.0751177	total: 814ms	remaining: 396ms
673:	learn: 0.0751120	total: 815ms	remaining: 394ms
674:	learn: 0.0750386	total: 816ms	remaining: 393ms
675:	learn: 0.0750237	total: 817ms	remaining: 392ms
676:	learn: 0.0749923	total: 819ms	remaining: 391ms
677:	learn: 0.0749230	total: 820ms	remaining: 389ms
678:	learn: 0.0748451	total: 821ms	remaining: 388ms
679:	learn: 0.0748377	total: 822ms	remaining: 387ms
680:	learn: 0.0748344	total: 823ms	remaining: 386ms
681:	learn: 0.0748315	total: 824ms	remaining: 384ms
682:	learn: 0.0748078	total: 825ms	remaining: 383ms
683:	learn: 0.0747761	total: 826ms	remaining: 382ms
684:	learn: 0.0747712	total: 828ms	remaining: 381ms
685:	learn: 0.0747678	total: 829ms	remaining: 379ms
686:	learn: 

841:	learn: 0.0685333	total: 996ms	remaining: 187ms
842:	learn: 0.0684541	total: 997ms	remaining: 186ms
843:	learn: 0.0683978	total: 998ms	remaining: 184ms
844:	learn: 0.0683344	total: 999ms	remaining: 183ms
845:	learn: 0.0683069	total: 1s	remaining: 182ms
846:	learn: 0.0682494	total: 1s	remaining: 181ms
847:	learn: 0.0682364	total: 1s	remaining: 180ms
848:	learn: 0.0681965	total: 1s	remaining: 178ms
849:	learn: 0.0681950	total: 1s	remaining: 177ms
850:	learn: 0.0681153	total: 1s	remaining: 176ms
851:	learn: 0.0681016	total: 1.01s	remaining: 175ms
852:	learn: 0.0680998	total: 1.01s	remaining: 174ms
853:	learn: 0.0680954	total: 1.01s	remaining: 172ms
854:	learn: 0.0680842	total: 1.01s	remaining: 171ms
855:	learn: 0.0680622	total: 1.01s	remaining: 170ms
856:	learn: 0.0679741	total: 1.01s	remaining: 169ms
857:	learn: 0.0679059	total: 1.01s	remaining: 168ms
858:	learn: 0.0678324	total: 1.01s	remaining: 167ms
859:	learn: 0.0678228	total: 1.01s	remaining: 165ms
860:	learn: 0.0678183	total: 1

0:	learn: 0.3760140	total: 1.17ms	remaining: 1.17s
1:	learn: 0.3592482	total: 2.48ms	remaining: 1.24s
2:	learn: 0.3452243	total: 3.46ms	remaining: 1.15s
3:	learn: 0.3321350	total: 4.36ms	remaining: 1.09s
4:	learn: 0.3193302	total: 5.54ms	remaining: 1.1s
5:	learn: 0.3048469	total: 6.62ms	remaining: 1.1s
6:	learn: 0.2943030	total: 7.93ms	remaining: 1.13s
7:	learn: 0.2852203	total: 9.27ms	remaining: 1.15s
8:	learn: 0.2744083	total: 10.4ms	remaining: 1.14s
9:	learn: 0.2657377	total: 11.4ms	remaining: 1.13s
10:	learn: 0.2571757	total: 12.4ms	remaining: 1.12s
11:	learn: 0.2498198	total: 13.6ms	remaining: 1.12s
12:	learn: 0.2429769	total: 14.7ms	remaining: 1.11s
13:	learn: 0.2362680	total: 15.7ms	remaining: 1.1s
14:	learn: 0.2299475	total: 16.6ms	remaining: 1.09s
15:	learn: 0.2246231	total: 17.7ms	remaining: 1.09s
16:	learn: 0.2191446	total: 18.9ms	remaining: 1.09s
17:	learn: 0.2134477	total: 20ms	remaining: 1.09s
18:	learn: 0.2078623	total: 21.1ms	remaining: 1.09s
19:	learn: 0.2038584	total:

175:	learn: 0.1047964	total: 196ms	remaining: 917ms
176:	learn: 0.1046513	total: 197ms	remaining: 917ms
177:	learn: 0.1046123	total: 198ms	remaining: 916ms
178:	learn: 0.1045439	total: 199ms	remaining: 915ms
179:	learn: 0.1043684	total: 200ms	remaining: 913ms
180:	learn: 0.1041712	total: 202ms	remaining: 912ms
181:	learn: 0.1040711	total: 203ms	remaining: 912ms
182:	learn: 0.1038584	total: 204ms	remaining: 910ms
183:	learn: 0.1036637	total: 205ms	remaining: 909ms
184:	learn: 0.1035717	total: 206ms	remaining: 908ms
185:	learn: 0.1034688	total: 207ms	remaining: 907ms
186:	learn: 0.1033320	total: 208ms	remaining: 906ms
187:	learn: 0.1031939	total: 210ms	remaining: 906ms
188:	learn: 0.1030630	total: 211ms	remaining: 905ms
189:	learn: 0.1030074	total: 212ms	remaining: 904ms
190:	learn: 0.1028538	total: 213ms	remaining: 903ms
191:	learn: 0.1027011	total: 214ms	remaining: 901ms
192:	learn: 0.1026330	total: 215ms	remaining: 900ms
193:	learn: 0.1025695	total: 216ms	remaining: 899ms
194:	learn: 

460:	learn: 0.0814221	total: 576ms	remaining: 674ms
461:	learn: 0.0813006	total: 577ms	remaining: 672ms
462:	learn: 0.0812665	total: 578ms	remaining: 671ms
463:	learn: 0.0811810	total: 579ms	remaining: 669ms
464:	learn: 0.0810680	total: 581ms	remaining: 668ms
465:	learn: 0.0810141	total: 581ms	remaining: 666ms
466:	learn: 0.0809585	total: 583ms	remaining: 665ms
467:	learn: 0.0809013	total: 584ms	remaining: 664ms
468:	learn: 0.0808947	total: 585ms	remaining: 662ms
469:	learn: 0.0808500	total: 586ms	remaining: 661ms
470:	learn: 0.0808174	total: 587ms	remaining: 659ms
471:	learn: 0.0807599	total: 588ms	remaining: 657ms
472:	learn: 0.0806247	total: 589ms	remaining: 656ms
473:	learn: 0.0805382	total: 590ms	remaining: 654ms
474:	learn: 0.0805272	total: 591ms	remaining: 653ms
475:	learn: 0.0805194	total: 592ms	remaining: 651ms
476:	learn: 0.0804920	total: 593ms	remaining: 650ms
477:	learn: 0.0804147	total: 594ms	remaining: 648ms
478:	learn: 0.0804000	total: 595ms	remaining: 647ms
479:	learn: 

758:	learn: 0.0684941	total: 943ms	remaining: 300ms
759:	learn: 0.0684739	total: 945ms	remaining: 298ms
760:	learn: 0.0684041	total: 946ms	remaining: 297ms
761:	learn: 0.0683458	total: 947ms	remaining: 296ms
762:	learn: 0.0683404	total: 948ms	remaining: 295ms
763:	learn: 0.0683290	total: 950ms	remaining: 293ms
764:	learn: 0.0682773	total: 951ms	remaining: 292ms
765:	learn: 0.0682198	total: 952ms	remaining: 291ms
766:	learn: 0.0681648	total: 953ms	remaining: 290ms
767:	learn: 0.0681302	total: 954ms	remaining: 288ms
768:	learn: 0.0681232	total: 956ms	remaining: 287ms
769:	learn: 0.0680869	total: 957ms	remaining: 286ms
770:	learn: 0.0680272	total: 958ms	remaining: 285ms
771:	learn: 0.0680010	total: 959ms	remaining: 283ms
772:	learn: 0.0679281	total: 960ms	remaining: 282ms
773:	learn: 0.0679034	total: 962ms	remaining: 281ms
774:	learn: 0.0678613	total: 963ms	remaining: 280ms
775:	learn: 0.0677998	total: 964ms	remaining: 278ms
776:	learn: 0.0677788	total: 973ms	remaining: 279ms
777:	learn: 

918:	learn: 0.0632112	total: 1.13s	remaining: 99.8ms
919:	learn: 0.0631481	total: 1.13s	remaining: 98.5ms
920:	learn: 0.0631296	total: 1.13s	remaining: 97.3ms
921:	learn: 0.0630949	total: 1.14s	remaining: 96.1ms
922:	learn: 0.0630923	total: 1.14s	remaining: 94.9ms
923:	learn: 0.0630356	total: 1.14s	remaining: 93.6ms
924:	learn: 0.0629748	total: 1.14s	remaining: 92.4ms
925:	learn: 0.0629203	total: 1.14s	remaining: 91.1ms
926:	learn: 0.0628646	total: 1.14s	remaining: 89.9ms
927:	learn: 0.0628403	total: 1.14s	remaining: 88.7ms
928:	learn: 0.0628098	total: 1.14s	remaining: 87.4ms
929:	learn: 0.0627475	total: 1.15s	remaining: 86.2ms
930:	learn: 0.0627092	total: 1.15s	remaining: 85ms
931:	learn: 0.0626402	total: 1.15s	remaining: 83.7ms
932:	learn: 0.0626074	total: 1.15s	remaining: 82.5ms
933:	learn: 0.0625738	total: 1.15s	remaining: 81.3ms
934:	learn: 0.0625328	total: 1.15s	remaining: 80ms
935:	learn: 0.0624471	total: 1.15s	remaining: 78.8ms
936:	learn: 0.0624425	total: 1.15s	remaining: 77.5

188:	learn: 0.1085074	total: 237ms	remaining: 1.02s
189:	learn: 0.1084691	total: 238ms	remaining: 1.01s
190:	learn: 0.1083902	total: 239ms	remaining: 1.01s
191:	learn: 0.1083730	total: 241ms	remaining: 1.01s
192:	learn: 0.1082832	total: 242ms	remaining: 1.01s
193:	learn: 0.1082371	total: 243ms	remaining: 1.01s
194:	learn: 0.1081513	total: 244ms	remaining: 1s
195:	learn: 0.1080927	total: 245ms	remaining: 1s
196:	learn: 0.1078706	total: 246ms	remaining: 1s
197:	learn: 0.1077128	total: 247ms	remaining: 1s
198:	learn: 0.1076663	total: 248ms	remaining: 998ms
199:	learn: 0.1076106	total: 249ms	remaining: 997ms
200:	learn: 0.1075143	total: 250ms	remaining: 994ms
201:	learn: 0.1073333	total: 251ms	remaining: 993ms
202:	learn: 0.1071675	total: 252ms	remaining: 990ms
203:	learn: 0.1069926	total: 253ms	remaining: 989ms
204:	learn: 0.1068495	total: 254ms	remaining: 987ms
205:	learn: 0.1066705	total: 256ms	remaining: 985ms
206:	learn: 0.1066458	total: 257ms	remaining: 984ms
207:	learn: 0.1065763	to

357:	learn: 0.0931606	total: 425ms	remaining: 762ms
358:	learn: 0.0930619	total: 426ms	remaining: 761ms
359:	learn: 0.0930317	total: 427ms	remaining: 760ms
360:	learn: 0.0930148	total: 428ms	remaining: 758ms
361:	learn: 0.0929984	total: 429ms	remaining: 757ms
362:	learn: 0.0928400	total: 431ms	remaining: 756ms
363:	learn: 0.0928042	total: 432ms	remaining: 755ms
364:	learn: 0.0927207	total: 433ms	remaining: 754ms
365:	learn: 0.0925237	total: 434ms	remaining: 753ms
366:	learn: 0.0924976	total: 436ms	remaining: 751ms
367:	learn: 0.0924076	total: 437ms	remaining: 751ms
368:	learn: 0.0923342	total: 439ms	remaining: 750ms
369:	learn: 0.0922448	total: 440ms	remaining: 749ms
370:	learn: 0.0921438	total: 441ms	remaining: 748ms
371:	learn: 0.0921222	total: 442ms	remaining: 747ms
372:	learn: 0.0920699	total: 443ms	remaining: 745ms
373:	learn: 0.0919974	total: 445ms	remaining: 744ms
374:	learn: 0.0919452	total: 446ms	remaining: 743ms
375:	learn: 0.0919186	total: 447ms	remaining: 742ms
376:	learn: 

637:	learn: 0.0774154	total: 793ms	remaining: 450ms
638:	learn: 0.0773592	total: 794ms	remaining: 449ms
639:	learn: 0.0773026	total: 795ms	remaining: 447ms
640:	learn: 0.0772945	total: 797ms	remaining: 446ms
641:	learn: 0.0772668	total: 798ms	remaining: 445ms
642:	learn: 0.0772402	total: 799ms	remaining: 443ms
643:	learn: 0.0772356	total: 800ms	remaining: 442ms
644:	learn: 0.0772332	total: 801ms	remaining: 441ms
645:	learn: 0.0772012	total: 802ms	remaining: 439ms
646:	learn: 0.0771149	total: 803ms	remaining: 438ms
647:	learn: 0.0770828	total: 804ms	remaining: 437ms
648:	learn: 0.0770589	total: 805ms	remaining: 435ms
649:	learn: 0.0770262	total: 806ms	remaining: 434ms
650:	learn: 0.0770223	total: 807ms	remaining: 433ms
651:	learn: 0.0770166	total: 808ms	remaining: 431ms
652:	learn: 0.0769308	total: 809ms	remaining: 430ms
653:	learn: 0.0768592	total: 810ms	remaining: 429ms
654:	learn: 0.0768562	total: 811ms	remaining: 427ms
655:	learn: 0.0767570	total: 813ms	remaining: 426ms
656:	learn: 

800:	learn: 0.0709696	total: 979ms	remaining: 243ms
801:	learn: 0.0709676	total: 980ms	remaining: 242ms
802:	learn: 0.0709196	total: 982ms	remaining: 241ms
803:	learn: 0.0708649	total: 983ms	remaining: 240ms
804:	learn: 0.0708116	total: 984ms	remaining: 238ms
805:	learn: 0.0708050	total: 985ms	remaining: 237ms
806:	learn: 0.0707875	total: 986ms	remaining: 236ms
807:	learn: 0.0707458	total: 987ms	remaining: 235ms
808:	learn: 0.0706948	total: 988ms	remaining: 233ms
809:	learn: 0.0706935	total: 989ms	remaining: 232ms
810:	learn: 0.0706202	total: 990ms	remaining: 231ms
811:	learn: 0.0705603	total: 991ms	remaining: 229ms
812:	learn: 0.0705550	total: 992ms	remaining: 228ms
813:	learn: 0.0705501	total: 993ms	remaining: 227ms
814:	learn: 0.0705326	total: 994ms	remaining: 226ms
815:	learn: 0.0705032	total: 996ms	remaining: 224ms
816:	learn: 0.0704376	total: 997ms	remaining: 223ms
817:	learn: 0.0703970	total: 998ms	remaining: 222ms
818:	learn: 0.0703632	total: 999ms	remaining: 221ms
819:	learn: 

982:	learn: 0.0653132	total: 1.17s	remaining: 20.2ms
983:	learn: 0.0652816	total: 1.17s	remaining: 19ms
984:	learn: 0.0652738	total: 1.17s	remaining: 17.8ms
985:	learn: 0.0652323	total: 1.17s	remaining: 16.6ms
986:	learn: 0.0651583	total: 1.17s	remaining: 15.4ms
987:	learn: 0.0651137	total: 1.17s	remaining: 14.3ms
988:	learn: 0.0651110	total: 1.17s	remaining: 13.1ms
989:	learn: 0.0650501	total: 1.18s	remaining: 11.9ms
990:	learn: 0.0650051	total: 1.18s	remaining: 10.7ms
991:	learn: 0.0650006	total: 1.18s	remaining: 9.5ms
992:	learn: 0.0649401	total: 1.18s	remaining: 8.31ms
993:	learn: 0.0649046	total: 1.18s	remaining: 7.13ms
994:	learn: 0.0648622	total: 1.18s	remaining: 5.94ms
995:	learn: 0.0648600	total: 1.18s	remaining: 4.75ms
996:	learn: 0.0648404	total: 1.18s	remaining: 3.56ms
997:	learn: 0.0648389	total: 1.18s	remaining: 2.37ms
998:	learn: 0.0647853	total: 1.19s	remaining: 1.19ms
999:	learn: 0.0647691	total: 1.19s	remaining: 0us
0:	learn: 0.3831878	total: 1.49ms	remaining: 1.49s
1

246:	learn: 0.0991352	total: 307ms	remaining: 935ms
247:	learn: 0.0990179	total: 308ms	remaining: 935ms
248:	learn: 0.0989715	total: 310ms	remaining: 934ms
249:	learn: 0.0988689	total: 311ms	remaining: 933ms
250:	learn: 0.0988253	total: 312ms	remaining: 931ms
251:	learn: 0.0987832	total: 313ms	remaining: 929ms
252:	learn: 0.0987403	total: 314ms	remaining: 927ms
253:	learn: 0.0985919	total: 315ms	remaining: 925ms
254:	learn: 0.0985594	total: 316ms	remaining: 923ms
255:	learn: 0.0984700	total: 317ms	remaining: 921ms
256:	learn: 0.0981504	total: 318ms	remaining: 919ms
257:	learn: 0.0980865	total: 319ms	remaining: 918ms
258:	learn: 0.0980071	total: 320ms	remaining: 916ms
259:	learn: 0.0978413	total: 322ms	remaining: 915ms
260:	learn: 0.0978131	total: 323ms	remaining: 914ms
261:	learn: 0.0977869	total: 324ms	remaining: 912ms
262:	learn: 0.0977746	total: 325ms	remaining: 910ms
263:	learn: 0.0976081	total: 326ms	remaining: 908ms
264:	learn: 0.0974954	total: 327ms	remaining: 907ms
265:	learn: 

418:	learn: 0.0859482	total: 491ms	remaining: 682ms
419:	learn: 0.0858491	total: 493ms	remaining: 680ms
420:	learn: 0.0858184	total: 494ms	remaining: 679ms
421:	learn: 0.0857413	total: 495ms	remaining: 678ms
422:	learn: 0.0856756	total: 496ms	remaining: 676ms
423:	learn: 0.0855790	total: 497ms	remaining: 675ms
424:	learn: 0.0855651	total: 498ms	remaining: 674ms
425:	learn: 0.0854393	total: 499ms	remaining: 672ms
426:	learn: 0.0853216	total: 500ms	remaining: 671ms
427:	learn: 0.0852216	total: 501ms	remaining: 669ms
428:	learn: 0.0851530	total: 502ms	remaining: 668ms
429:	learn: 0.0850771	total: 503ms	remaining: 666ms
430:	learn: 0.0849636	total: 504ms	remaining: 665ms
431:	learn: 0.0849025	total: 505ms	remaining: 664ms
432:	learn: 0.0847229	total: 506ms	remaining: 663ms
433:	learn: 0.0847196	total: 507ms	remaining: 662ms
434:	learn: 0.0847092	total: 508ms	remaining: 660ms
435:	learn: 0.0846641	total: 509ms	remaining: 659ms
436:	learn: 0.0845350	total: 510ms	remaining: 658ms
437:	learn: 

597:	learn: 0.0761912	total: 679ms	remaining: 456ms
598:	learn: 0.0761880	total: 680ms	remaining: 455ms
599:	learn: 0.0761817	total: 681ms	remaining: 454ms
600:	learn: 0.0761695	total: 682ms	remaining: 453ms
601:	learn: 0.0760529	total: 684ms	remaining: 452ms
602:	learn: 0.0760151	total: 685ms	remaining: 451ms
603:	learn: 0.0760075	total: 686ms	remaining: 450ms
604:	learn: 0.0759382	total: 687ms	remaining: 449ms
605:	learn: 0.0758432	total: 688ms	remaining: 447ms
606:	learn: 0.0758337	total: 689ms	remaining: 446ms
607:	learn: 0.0757916	total: 691ms	remaining: 445ms
608:	learn: 0.0757242	total: 692ms	remaining: 444ms
609:	learn: 0.0756472	total: 693ms	remaining: 443ms
610:	learn: 0.0755758	total: 694ms	remaining: 442ms
611:	learn: 0.0754985	total: 696ms	remaining: 441ms
612:	learn: 0.0754343	total: 697ms	remaining: 440ms
613:	learn: 0.0754034	total: 698ms	remaining: 439ms
614:	learn: 0.0753866	total: 700ms	remaining: 438ms
615:	learn: 0.0753714	total: 701ms	remaining: 437ms
616:	learn: 

755:	learn: 0.0698286	total: 869ms	remaining: 281ms
756:	learn: 0.0697889	total: 871ms	remaining: 279ms
757:	learn: 0.0697432	total: 872ms	remaining: 278ms
758:	learn: 0.0697081	total: 873ms	remaining: 277ms
759:	learn: 0.0696784	total: 874ms	remaining: 276ms
760:	learn: 0.0696743	total: 875ms	remaining: 275ms
761:	learn: 0.0696304	total: 876ms	remaining: 274ms
762:	learn: 0.0695329	total: 877ms	remaining: 272ms
763:	learn: 0.0695235	total: 878ms	remaining: 271ms
764:	learn: 0.0694779	total: 879ms	remaining: 270ms
765:	learn: 0.0694426	total: 880ms	remaining: 269ms
766:	learn: 0.0693924	total: 882ms	remaining: 268ms
767:	learn: 0.0693127	total: 883ms	remaining: 267ms
768:	learn: 0.0692659	total: 884ms	remaining: 266ms
769:	learn: 0.0692021	total: 886ms	remaining: 265ms
770:	learn: 0.0691428	total: 886ms	remaining: 263ms
771:	learn: 0.0690926	total: 887ms	remaining: 262ms
772:	learn: 0.0690705	total: 888ms	remaining: 261ms
773:	learn: 0.0690652	total: 890ms	remaining: 260ms
774:	learn: 

918:	learn: 0.0646212	total: 1.05s	remaining: 92.9ms
919:	learn: 0.0645637	total: 1.05s	remaining: 91.8ms
920:	learn: 0.0645461	total: 1.06s	remaining: 90.7ms
921:	learn: 0.0644664	total: 1.06s	remaining: 89.6ms
922:	learn: 0.0644356	total: 1.06s	remaining: 88.4ms
923:	learn: 0.0644162	total: 1.06s	remaining: 87.3ms
924:	learn: 0.0643972	total: 1.06s	remaining: 86.1ms
925:	learn: 0.0643561	total: 1.06s	remaining: 84.9ms
926:	learn: 0.0643315	total: 1.06s	remaining: 83.8ms
927:	learn: 0.0642934	total: 1.06s	remaining: 82.6ms
928:	learn: 0.0642647	total: 1.07s	remaining: 81.5ms
929:	learn: 0.0642329	total: 1.07s	remaining: 80.3ms
930:	learn: 0.0642307	total: 1.07s	remaining: 79.2ms
931:	learn: 0.0641953	total: 1.07s	remaining: 78ms
932:	learn: 0.0641413	total: 1.07s	remaining: 76.9ms
933:	learn: 0.0641181	total: 1.07s	remaining: 75.7ms
934:	learn: 0.0640529	total: 1.07s	remaining: 74.6ms
935:	learn: 0.0640486	total: 1.07s	remaining: 73.4ms
936:	learn: 0.0640367	total: 1.07s	remaining: 72

230:	learn: 0.1032157	total: 258ms	remaining: 859ms
231:	learn: 0.1031786	total: 259ms	remaining: 858ms
232:	learn: 0.1031314	total: 261ms	remaining: 860ms
233:	learn: 0.1030791	total: 262ms	remaining: 859ms
234:	learn: 0.1029168	total: 263ms	remaining: 858ms
235:	learn: 0.1027915	total: 265ms	remaining: 857ms
236:	learn: 0.1026874	total: 266ms	remaining: 856ms
237:	learn: 0.1026633	total: 267ms	remaining: 855ms
238:	learn: 0.1024696	total: 268ms	remaining: 854ms
239:	learn: 0.1023962	total: 269ms	remaining: 853ms
240:	learn: 0.1023551	total: 270ms	remaining: 852ms
241:	learn: 0.1023387	total: 272ms	remaining: 850ms
242:	learn: 0.1021875	total: 273ms	remaining: 850ms
243:	learn: 0.1021321	total: 274ms	remaining: 849ms
244:	learn: 0.1019972	total: 275ms	remaining: 848ms
245:	learn: 0.1018370	total: 276ms	remaining: 847ms
246:	learn: 0.1016907	total: 277ms	remaining: 846ms
247:	learn: 0.1015992	total: 279ms	remaining: 845ms
248:	learn: 0.1015763	total: 280ms	remaining: 845ms
249:	learn: 

543:	learn: 0.0822036	total: 636ms	remaining: 533ms
544:	learn: 0.0821960	total: 637ms	remaining: 532ms
545:	learn: 0.0821927	total: 638ms	remaining: 531ms
546:	learn: 0.0821393	total: 640ms	remaining: 530ms
547:	learn: 0.0821244	total: 640ms	remaining: 528ms
548:	learn: 0.0820160	total: 642ms	remaining: 527ms
549:	learn: 0.0819787	total: 643ms	remaining: 526ms
550:	learn: 0.0819181	total: 644ms	remaining: 525ms
551:	learn: 0.0818188	total: 645ms	remaining: 524ms
552:	learn: 0.0818149	total: 647ms	remaining: 523ms
553:	learn: 0.0818061	total: 648ms	remaining: 522ms
554:	learn: 0.0817579	total: 649ms	remaining: 521ms
555:	learn: 0.0817043	total: 650ms	remaining: 519ms
556:	learn: 0.0816492	total: 651ms	remaining: 518ms
557:	learn: 0.0816324	total: 653ms	remaining: 517ms
558:	learn: 0.0815878	total: 654ms	remaining: 516ms
559:	learn: 0.0814813	total: 655ms	remaining: 515ms
560:	learn: 0.0814757	total: 656ms	remaining: 514ms
561:	learn: 0.0813785	total: 658ms	remaining: 513ms
562:	learn: 

814:	learn: 0.0713838	total: 1s	remaining: 228ms
815:	learn: 0.0713790	total: 1s	remaining: 226ms
816:	learn: 0.0713744	total: 1s	remaining: 225ms
817:	learn: 0.0713490	total: 1.01s	remaining: 224ms
818:	learn: 0.0713474	total: 1.01s	remaining: 223ms
819:	learn: 0.0712947	total: 1.01s	remaining: 221ms
820:	learn: 0.0712625	total: 1.01s	remaining: 220ms
821:	learn: 0.0711722	total: 1.01s	remaining: 219ms
822:	learn: 0.0711683	total: 1.01s	remaining: 218ms
823:	learn: 0.0711222	total: 1.01s	remaining: 216ms
824:	learn: 0.0710689	total: 1.01s	remaining: 215ms
825:	learn: 0.0710333	total: 1.01s	remaining: 214ms
826:	learn: 0.0709918	total: 1.01s	remaining: 213ms
827:	learn: 0.0709685	total: 1.02s	remaining: 211ms
828:	learn: 0.0709113	total: 1.02s	remaining: 210ms
829:	learn: 0.0708934	total: 1.02s	remaining: 209ms
830:	learn: 0.0708450	total: 1.02s	remaining: 208ms
831:	learn: 0.0707627	total: 1.02s	remaining: 206ms
832:	learn: 0.0707227	total: 1.02s	remaining: 205ms
833:	learn: 0.0706860

986:	learn: 0.0653882	total: 1.19s	remaining: 15.7ms
987:	learn: 0.0653149	total: 1.19s	remaining: 14.5ms
988:	learn: 0.0652681	total: 1.19s	remaining: 13.3ms
989:	learn: 0.0652469	total: 1.2s	remaining: 12.1ms
990:	learn: 0.0652285	total: 1.2s	remaining: 10.9ms
991:	learn: 0.0652018	total: 1.2s	remaining: 9.66ms
992:	learn: 0.0651675	total: 1.2s	remaining: 8.45ms
993:	learn: 0.0651530	total: 1.2s	remaining: 7.24ms
994:	learn: 0.0651179	total: 1.2s	remaining: 6.03ms
995:	learn: 0.0651134	total: 1.2s	remaining: 4.83ms
996:	learn: 0.0650409	total: 1.2s	remaining: 3.62ms
997:	learn: 0.0650182	total: 1.2s	remaining: 2.41ms
998:	learn: 0.0650000	total: 1.21s	remaining: 1.21ms
999:	learn: 0.0649145	total: 1.21s	remaining: 0us
0:	learn: 0.3789510	total: 1.34ms	remaining: 1.34s
1:	learn: 0.3601840	total: 2.56ms	remaining: 1.28s
2:	learn: 0.3464575	total: 3.55ms	remaining: 1.18s
3:	learn: 0.3320908	total: 4.65ms	remaining: 1.16s
4:	learn: 0.3204003	total: 5.7ms	remaining: 1.13s
5:	learn: 0.3102

256:	learn: 0.1004759	total: 312ms	remaining: 902ms
257:	learn: 0.1004410	total: 313ms	remaining: 901ms
258:	learn: 0.1002627	total: 315ms	remaining: 900ms
259:	learn: 0.1002324	total: 316ms	remaining: 899ms
260:	learn: 0.1000921	total: 317ms	remaining: 898ms
261:	learn: 0.1000613	total: 318ms	remaining: 897ms
262:	learn: 0.0998917	total: 319ms	remaining: 895ms
263:	learn: 0.0998638	total: 320ms	remaining: 893ms
264:	learn: 0.0998254	total: 322ms	remaining: 892ms
265:	learn: 0.0996494	total: 323ms	remaining: 891ms
266:	learn: 0.0996319	total: 324ms	remaining: 889ms
267:	learn: 0.0994674	total: 325ms	remaining: 888ms
268:	learn: 0.0994354	total: 326ms	remaining: 886ms
269:	learn: 0.0993975	total: 327ms	remaining: 885ms
270:	learn: 0.0993881	total: 328ms	remaining: 883ms
271:	learn: 0.0993559	total: 329ms	remaining: 881ms
272:	learn: 0.0992559	total: 330ms	remaining: 880ms
273:	learn: 0.0990918	total: 332ms	remaining: 878ms
274:	learn: 0.0990599	total: 333ms	remaining: 877ms
275:	learn: 

417:	learn: 0.0892459	total: 493ms	remaining: 686ms
418:	learn: 0.0892169	total: 494ms	remaining: 685ms
419:	learn: 0.0892044	total: 496ms	remaining: 685ms
420:	learn: 0.0891053	total: 497ms	remaining: 684ms
421:	learn: 0.0890061	total: 498ms	remaining: 682ms
422:	learn: 0.0888379	total: 499ms	remaining: 681ms
423:	learn: 0.0887742	total: 500ms	remaining: 680ms
424:	learn: 0.0887075	total: 501ms	remaining: 678ms
425:	learn: 0.0887034	total: 502ms	remaining: 677ms
426:	learn: 0.0885511	total: 504ms	remaining: 676ms
427:	learn: 0.0884555	total: 505ms	remaining: 674ms
428:	learn: 0.0884245	total: 506ms	remaining: 673ms
429:	learn: 0.0883213	total: 507ms	remaining: 672ms
430:	learn: 0.0883062	total: 508ms	remaining: 670ms
431:	learn: 0.0882948	total: 509ms	remaining: 669ms
432:	learn: 0.0881742	total: 510ms	remaining: 668ms
433:	learn: 0.0881588	total: 511ms	remaining: 667ms
434:	learn: 0.0881530	total: 512ms	remaining: 665ms
435:	learn: 0.0880696	total: 513ms	remaining: 664ms
436:	learn: 

585:	learn: 0.0797243	total: 679ms	remaining: 480ms
586:	learn: 0.0796752	total: 681ms	remaining: 479ms
587:	learn: 0.0795846	total: 682ms	remaining: 478ms
588:	learn: 0.0795320	total: 683ms	remaining: 477ms
589:	learn: 0.0795151	total: 684ms	remaining: 476ms
590:	learn: 0.0794543	total: 685ms	remaining: 474ms
591:	learn: 0.0793838	total: 687ms	remaining: 473ms
592:	learn: 0.0793274	total: 688ms	remaining: 472ms
593:	learn: 0.0792164	total: 689ms	remaining: 471ms
594:	learn: 0.0791859	total: 690ms	remaining: 469ms
595:	learn: 0.0791230	total: 691ms	remaining: 468ms
596:	learn: 0.0789964	total: 692ms	remaining: 467ms
597:	learn: 0.0789817	total: 693ms	remaining: 466ms
598:	learn: 0.0789204	total: 694ms	remaining: 465ms
599:	learn: 0.0788702	total: 695ms	remaining: 464ms
600:	learn: 0.0788410	total: 696ms	remaining: 462ms
601:	learn: 0.0787913	total: 698ms	remaining: 461ms
602:	learn: 0.0787880	total: 699ms	remaining: 460ms
603:	learn: 0.0787649	total: 700ms	remaining: 459ms
604:	learn: 

753:	learn: 0.0727210	total: 866ms	remaining: 282ms
754:	learn: 0.0726455	total: 867ms	remaining: 281ms
755:	learn: 0.0726359	total: 868ms	remaining: 280ms
756:	learn: 0.0726178	total: 869ms	remaining: 279ms
757:	learn: 0.0725967	total: 871ms	remaining: 278ms
758:	learn: 0.0725778	total: 872ms	remaining: 277ms
759:	learn: 0.0725724	total: 873ms	remaining: 276ms
760:	learn: 0.0725629	total: 874ms	remaining: 274ms
761:	learn: 0.0725551	total: 875ms	remaining: 273ms
762:	learn: 0.0725534	total: 876ms	remaining: 272ms
763:	learn: 0.0725260	total: 877ms	remaining: 271ms
764:	learn: 0.0724900	total: 879ms	remaining: 270ms
765:	learn: 0.0724723	total: 880ms	remaining: 269ms
766:	learn: 0.0724318	total: 881ms	remaining: 268ms
767:	learn: 0.0723997	total: 882ms	remaining: 266ms
768:	learn: 0.0723356	total: 883ms	remaining: 265ms
769:	learn: 0.0722472	total: 885ms	remaining: 264ms
770:	learn: 0.0722025	total: 886ms	remaining: 263ms
771:	learn: 0.0721962	total: 887ms	remaining: 262ms
772:	learn: 

0:	learn: 0.3836021	total: 1.27ms	remaining: 1.27s
1:	learn: 0.3668380	total: 2.94ms	remaining: 1.47s
2:	learn: 0.3506750	total: 3.93ms	remaining: 1.3s
3:	learn: 0.3374325	total: 4.92ms	remaining: 1.22s
4:	learn: 0.3247897	total: 6.74ms	remaining: 1.34s
5:	learn: 0.3116465	total: 7.95ms	remaining: 1.32s
6:	learn: 0.3018818	total: 10.1ms	remaining: 1.44s
7:	learn: 0.2923552	total: 11.2ms	remaining: 1.39s
8:	learn: 0.2823232	total: 12.5ms	remaining: 1.37s
9:	learn: 0.2728133	total: 13.7ms	remaining: 1.36s
10:	learn: 0.2638861	total: 15.1ms	remaining: 1.36s
11:	learn: 0.2551247	total: 16.4ms	remaining: 1.35s
12:	learn: 0.2477638	total: 17.7ms	remaining: 1.34s
13:	learn: 0.2403628	total: 19ms	remaining: 1.34s
14:	learn: 0.2335399	total: 20.1ms	remaining: 1.32s
15:	learn: 0.2279300	total: 21.3ms	remaining: 1.31s
16:	learn: 0.2234867	total: 22.6ms	remaining: 1.31s
17:	learn: 0.2181447	total: 23.9ms	remaining: 1.3s
18:	learn: 0.2134954	total: 25ms	remaining: 1.29s
19:	learn: 0.2101981	total: 

161:	learn: 0.1115985	total: 182ms	remaining: 944ms
162:	learn: 0.1115378	total: 184ms	remaining: 943ms
163:	learn: 0.1113808	total: 185ms	remaining: 943ms
164:	learn: 0.1111819	total: 186ms	remaining: 942ms
165:	learn: 0.1111099	total: 187ms	remaining: 940ms
166:	learn: 0.1108996	total: 188ms	remaining: 939ms
167:	learn: 0.1108494	total: 190ms	remaining: 939ms
168:	learn: 0.1107794	total: 191ms	remaining: 937ms
169:	learn: 0.1105376	total: 192ms	remaining: 936ms
170:	learn: 0.1105099	total: 193ms	remaining: 935ms
171:	learn: 0.1102356	total: 194ms	remaining: 934ms
172:	learn: 0.1102133	total: 195ms	remaining: 932ms
173:	learn: 0.1101347	total: 196ms	remaining: 931ms
174:	learn: 0.1099634	total: 197ms	remaining: 930ms
175:	learn: 0.1099149	total: 199ms	remaining: 930ms
176:	learn: 0.1098140	total: 200ms	remaining: 928ms
177:	learn: 0.1097404	total: 201ms	remaining: 927ms
178:	learn: 0.1096965	total: 202ms	remaining: 925ms
179:	learn: 0.1094658	total: 203ms	remaining: 924ms
180:	learn: 

330:	learn: 0.0942652	total: 370ms	remaining: 747ms
331:	learn: 0.0942196	total: 371ms	remaining: 746ms
332:	learn: 0.0941247	total: 372ms	remaining: 746ms
333:	learn: 0.0939726	total: 374ms	remaining: 745ms
334:	learn: 0.0937967	total: 375ms	remaining: 744ms
335:	learn: 0.0937723	total: 376ms	remaining: 743ms
336:	learn: 0.0937505	total: 377ms	remaining: 742ms
337:	learn: 0.0936343	total: 379ms	remaining: 742ms
338:	learn: 0.0934457	total: 380ms	remaining: 741ms
339:	learn: 0.0934294	total: 381ms	remaining: 739ms
340:	learn: 0.0934000	total: 382ms	remaining: 739ms
341:	learn: 0.0933800	total: 383ms	remaining: 738ms
342:	learn: 0.0932680	total: 385ms	remaining: 737ms
343:	learn: 0.0932099	total: 386ms	remaining: 736ms
344:	learn: 0.0931867	total: 387ms	remaining: 734ms
345:	learn: 0.0931463	total: 388ms	remaining: 733ms
346:	learn: 0.0929827	total: 390ms	remaining: 733ms
347:	learn: 0.0928969	total: 391ms	remaining: 732ms
348:	learn: 0.0928058	total: 392ms	remaining: 731ms
349:	learn: 

493:	learn: 0.0827682	total: 557ms	remaining: 571ms
494:	learn: 0.0826840	total: 559ms	remaining: 570ms
495:	learn: 0.0826095	total: 561ms	remaining: 570ms
496:	learn: 0.0825987	total: 562ms	remaining: 569ms
497:	learn: 0.0825057	total: 563ms	remaining: 567ms
498:	learn: 0.0824956	total: 564ms	remaining: 566ms
499:	learn: 0.0824393	total: 565ms	remaining: 565ms
500:	learn: 0.0823326	total: 567ms	remaining: 564ms
501:	learn: 0.0822439	total: 568ms	remaining: 563ms
502:	learn: 0.0821753	total: 569ms	remaining: 562ms
503:	learn: 0.0821692	total: 570ms	remaining: 561ms
504:	learn: 0.0821638	total: 571ms	remaining: 560ms
505:	learn: 0.0820742	total: 573ms	remaining: 559ms
506:	learn: 0.0819808	total: 576ms	remaining: 561ms
507:	learn: 0.0819582	total: 578ms	remaining: 560ms
508:	learn: 0.0819035	total: 584ms	remaining: 563ms
509:	learn: 0.0818830	total: 585ms	remaining: 562ms
510:	learn: 0.0818730	total: 587ms	remaining: 562ms
511:	learn: 0.0818488	total: 589ms	remaining: 561ms
512:	learn: 

804:	learn: 0.0686005	total: 933ms	remaining: 226ms
805:	learn: 0.0685732	total: 934ms	remaining: 225ms
806:	learn: 0.0685179	total: 935ms	remaining: 224ms
807:	learn: 0.0685142	total: 937ms	remaining: 223ms
808:	learn: 0.0684942	total: 938ms	remaining: 221ms
809:	learn: 0.0684895	total: 939ms	remaining: 220ms
810:	learn: 0.0684599	total: 940ms	remaining: 219ms
811:	learn: 0.0683670	total: 941ms	remaining: 218ms
812:	learn: 0.0683532	total: 942ms	remaining: 217ms
813:	learn: 0.0683476	total: 943ms	remaining: 216ms
814:	learn: 0.0683057	total: 944ms	remaining: 214ms
815:	learn: 0.0682877	total: 946ms	remaining: 213ms
816:	learn: 0.0682051	total: 947ms	remaining: 212ms
817:	learn: 0.0681558	total: 948ms	remaining: 211ms
818:	learn: 0.0681170	total: 949ms	remaining: 210ms
819:	learn: 0.0680328	total: 951ms	remaining: 209ms
820:	learn: 0.0680313	total: 952ms	remaining: 207ms
821:	learn: 0.0679395	total: 953ms	remaining: 206ms
822:	learn: 0.0679137	total: 954ms	remaining: 205ms
823:	learn: 

983:	learn: 0.0623176	total: 1.12s	remaining: 18.2ms
984:	learn: 0.0622692	total: 1.12s	remaining: 17.1ms
985:	learn: 0.0622561	total: 1.12s	remaining: 15.9ms
986:	learn: 0.0622386	total: 1.12s	remaining: 14.8ms
987:	learn: 0.0622196	total: 1.13s	remaining: 13.7ms
988:	learn: 0.0622056	total: 1.13s	remaining: 12.5ms
989:	learn: 0.0621311	total: 1.13s	remaining: 11.4ms
990:	learn: 0.0621107	total: 1.13s	remaining: 10.3ms
991:	learn: 0.0620913	total: 1.13s	remaining: 9.11ms
992:	learn: 0.0620792	total: 1.13s	remaining: 7.97ms
993:	learn: 0.0620434	total: 1.13s	remaining: 6.84ms
994:	learn: 0.0620169	total: 1.13s	remaining: 5.7ms
995:	learn: 0.0619766	total: 1.14s	remaining: 4.56ms
996:	learn: 0.0619219	total: 1.14s	remaining: 3.42ms
997:	learn: 0.0618445	total: 1.14s	remaining: 2.28ms
998:	learn: 0.0618048	total: 1.14s	remaining: 1.14ms
999:	learn: 0.0617701	total: 1.14s	remaining: 0us
0:	learn: 0.3820787	total: 1.13ms	remaining: 1.13s
1:	learn: 0.3652293	total: 2.31ms	remaining: 1.15s
2

228:	learn: 0.1042210	total: 313ms	remaining: 1.05s
229:	learn: 0.1040496	total: 314ms	remaining: 1.05s
230:	learn: 0.1039623	total: 316ms	remaining: 1.05s
231:	learn: 0.1039181	total: 318ms	remaining: 1.05s
232:	learn: 0.1038680	total: 321ms	remaining: 1.05s
233:	learn: 0.1037928	total: 322ms	remaining: 1.05s
234:	learn: 0.1037472	total: 324ms	remaining: 1.05s
235:	learn: 0.1035792	total: 327ms	remaining: 1.06s
236:	learn: 0.1033806	total: 329ms	remaining: 1.06s
237:	learn: 0.1033477	total: 330ms	remaining: 1.06s
238:	learn: 0.1031669	total: 342ms	remaining: 1.09s
239:	learn: 0.1029138	total: 344ms	remaining: 1.09s
240:	learn: 0.1028285	total: 346ms	remaining: 1.09s
241:	learn: 0.1028192	total: 347ms	remaining: 1.09s
242:	learn: 0.1026376	total: 349ms	remaining: 1.09s
243:	learn: 0.1024511	total: 351ms	remaining: 1.09s
244:	learn: 0.1023479	total: 353ms	remaining: 1.09s
245:	learn: 0.1023171	total: 356ms	remaining: 1.09s
246:	learn: 0.1022804	total: 358ms	remaining: 1.09s
247:	learn: 

492:	learn: 0.0845522	total: 683ms	remaining: 702ms
493:	learn: 0.0844563	total: 684ms	remaining: 700ms
494:	learn: 0.0843865	total: 685ms	remaining: 699ms
495:	learn: 0.0842798	total: 698ms	remaining: 709ms
496:	learn: 0.0842274	total: 699ms	remaining: 707ms
497:	learn: 0.0842215	total: 699ms	remaining: 705ms
498:	learn: 0.0841168	total: 700ms	remaining: 703ms
499:	learn: 0.0840889	total: 702ms	remaining: 702ms
500:	learn: 0.0840096	total: 703ms	remaining: 700ms
501:	learn: 0.0838375	total: 704ms	remaining: 699ms
502:	learn: 0.0838334	total: 705ms	remaining: 697ms
503:	learn: 0.0838247	total: 706ms	remaining: 695ms
504:	learn: 0.0838109	total: 707ms	remaining: 693ms
505:	learn: 0.0837024	total: 708ms	remaining: 692ms
506:	learn: 0.0836380	total: 710ms	remaining: 690ms
507:	learn: 0.0836329	total: 711ms	remaining: 688ms
508:	learn: 0.0835612	total: 712ms	remaining: 686ms
509:	learn: 0.0835043	total: 713ms	remaining: 685ms
510:	learn: 0.0834983	total: 714ms	remaining: 683ms
511:	learn: 

787:	learn: 0.0715816	total: 1.05s	remaining: 283ms
788:	learn: 0.0715786	total: 1.05s	remaining: 282ms
789:	learn: 0.0715759	total: 1.05s	remaining: 280ms
790:	learn: 0.0715068	total: 1.05s	remaining: 279ms
791:	learn: 0.0714624	total: 1.06s	remaining: 278ms
792:	learn: 0.0714291	total: 1.06s	remaining: 276ms
793:	learn: 0.0714108	total: 1.06s	remaining: 275ms
794:	learn: 0.0713882	total: 1.06s	remaining: 273ms
795:	learn: 0.0713675	total: 1.06s	remaining: 272ms
796:	learn: 0.0713279	total: 1.06s	remaining: 271ms
797:	learn: 0.0713230	total: 1.06s	remaining: 269ms
798:	learn: 0.0712430	total: 1.06s	remaining: 268ms
799:	learn: 0.0711585	total: 1.06s	remaining: 266ms
800:	learn: 0.0711549	total: 1.07s	remaining: 265ms
801:	learn: 0.0711509	total: 1.07s	remaining: 264ms
802:	learn: 0.0711399	total: 1.07s	remaining: 262ms
803:	learn: 0.0711041	total: 1.07s	remaining: 261ms
804:	learn: 0.0710773	total: 1.07s	remaining: 260ms
805:	learn: 0.0710708	total: 1.07s	remaining: 258ms
806:	learn: 

951:	learn: 0.0661433	total: 1.24s	remaining: 62.6ms
952:	learn: 0.0661373	total: 1.24s	remaining: 61.3ms
953:	learn: 0.0661199	total: 1.24s	remaining: 60ms
954:	learn: 0.0661002	total: 1.24s	remaining: 58.7ms
955:	learn: 0.0660420	total: 1.25s	remaining: 57.4ms
956:	learn: 0.0660186	total: 1.25s	remaining: 56ms
957:	learn: 0.0660159	total: 1.25s	remaining: 54.7ms
958:	learn: 0.0659879	total: 1.25s	remaining: 53.4ms
959:	learn: 0.0659860	total: 1.25s	remaining: 52.1ms
960:	learn: 0.0659520	total: 1.25s	remaining: 50.8ms
961:	learn: 0.0659476	total: 1.25s	remaining: 49.5ms
962:	learn: 0.0659237	total: 1.25s	remaining: 48.2ms
963:	learn: 0.0658953	total: 1.25s	remaining: 46.8ms
964:	learn: 0.0658550	total: 1.25s	remaining: 45.5ms
965:	learn: 0.0658530	total: 1.26s	remaining: 44.2ms
966:	learn: 0.0658116	total: 1.26s	remaining: 42.9ms
967:	learn: 0.0658098	total: 1.26s	remaining: 41.6ms
968:	learn: 0.0657797	total: 1.26s	remaining: 40.3ms
969:	learn: 0.0657126	total: 1.26s	remaining: 39ms

198:	learn: 0.1083640	total: 266ms	remaining: 1.07s
199:	learn: 0.1083179	total: 267ms	remaining: 1.07s
200:	learn: 0.1080875	total: 270ms	remaining: 1.07s
201:	learn: 0.1080702	total: 271ms	remaining: 1.07s
202:	learn: 0.1078333	total: 272ms	remaining: 1.07s
203:	learn: 0.1075830	total: 273ms	remaining: 1.07s
204:	learn: 0.1074671	total: 275ms	remaining: 1.07s
205:	learn: 0.1074315	total: 277ms	remaining: 1.07s
206:	learn: 0.1073504	total: 278ms	remaining: 1.06s
207:	learn: 0.1072138	total: 279ms	remaining: 1.06s
208:	learn: 0.1071942	total: 280ms	remaining: 1.06s
209:	learn: 0.1071401	total: 281ms	remaining: 1.06s
210:	learn: 0.1071160	total: 283ms	remaining: 1.06s
211:	learn: 0.1068735	total: 284ms	remaining: 1.05s
212:	learn: 0.1068075	total: 285ms	remaining: 1.05s
213:	learn: 0.1066754	total: 286ms	remaining: 1.05s
214:	learn: 0.1066615	total: 288ms	remaining: 1.05s
215:	learn: 0.1066345	total: 289ms	remaining: 1.05s
216:	learn: 0.1065689	total: 290ms	remaining: 1.05s
217:	learn: 

493:	learn: 0.0846067	total: 641ms	remaining: 656ms
494:	learn: 0.0845054	total: 642ms	remaining: 655ms
495:	learn: 0.0844915	total: 644ms	remaining: 654ms
496:	learn: 0.0843870	total: 645ms	remaining: 653ms
497:	learn: 0.0842941	total: 646ms	remaining: 652ms
498:	learn: 0.0841721	total: 648ms	remaining: 650ms
499:	learn: 0.0841585	total: 649ms	remaining: 649ms
500:	learn: 0.0840775	total: 650ms	remaining: 648ms
501:	learn: 0.0840579	total: 651ms	remaining: 646ms
502:	learn: 0.0839844	total: 653ms	remaining: 645ms
503:	learn: 0.0839436	total: 654ms	remaining: 644ms
504:	learn: 0.0839139	total: 655ms	remaining: 643ms
505:	learn: 0.0837677	total: 657ms	remaining: 641ms
506:	learn: 0.0837628	total: 658ms	remaining: 640ms
507:	learn: 0.0837329	total: 659ms	remaining: 639ms
508:	learn: 0.0837215	total: 671ms	remaining: 647ms
509:	learn: 0.0837098	total: 673ms	remaining: 646ms
510:	learn: 0.0836998	total: 675ms	remaining: 646ms
511:	learn: 0.0836418	total: 677ms	remaining: 645ms
512:	learn: 

739:	learn: 0.0745603	total: 1.01s	remaining: 356ms
740:	learn: 0.0745562	total: 1.01s	remaining: 355ms
741:	learn: 0.0745395	total: 1.01s	remaining: 353ms
742:	learn: 0.0745352	total: 1.02s	remaining: 352ms
743:	learn: 0.0745113	total: 1.02s	remaining: 350ms
744:	learn: 0.0744249	total: 1.02s	remaining: 349ms
745:	learn: 0.0744070	total: 1.02s	remaining: 347ms
746:	learn: 0.0743426	total: 1.02s	remaining: 346ms
747:	learn: 0.0743359	total: 1.02s	remaining: 344ms
748:	learn: 0.0743174	total: 1.02s	remaining: 343ms
749:	learn: 0.0743123	total: 1.02s	remaining: 342ms
750:	learn: 0.0742697	total: 1.03s	remaining: 340ms
751:	learn: 0.0742178	total: 1.03s	remaining: 339ms
752:	learn: 0.0741593	total: 1.03s	remaining: 337ms
753:	learn: 0.0741537	total: 1.03s	remaining: 336ms
754:	learn: 0.0740564	total: 1.03s	remaining: 334ms
755:	learn: 0.0740501	total: 1.03s	remaining: 333ms
756:	learn: 0.0740362	total: 1.03s	remaining: 332ms
757:	learn: 0.0740340	total: 1.03s	remaining: 330ms
758:	learn: 

901:	learn: 0.0689150	total: 1.2s	remaining: 130ms
902:	learn: 0.0688699	total: 1.2s	remaining: 129ms
903:	learn: 0.0688460	total: 1.2s	remaining: 128ms
904:	learn: 0.0687723	total: 1.2s	remaining: 126ms
905:	learn: 0.0687419	total: 1.21s	remaining: 125ms
906:	learn: 0.0687042	total: 1.21s	remaining: 124ms
907:	learn: 0.0687021	total: 1.21s	remaining: 122ms
908:	learn: 0.0686919	total: 1.21s	remaining: 121ms
909:	learn: 0.0686524	total: 1.21s	remaining: 120ms
910:	learn: 0.0685803	total: 1.21s	remaining: 118ms
911:	learn: 0.0685783	total: 1.21s	remaining: 117ms
912:	learn: 0.0685282	total: 1.21s	remaining: 116ms
913:	learn: 0.0684648	total: 1.22s	remaining: 114ms
914:	learn: 0.0684442	total: 1.22s	remaining: 113ms
915:	learn: 0.0684411	total: 1.22s	remaining: 112ms
916:	learn: 0.0683893	total: 1.22s	remaining: 110ms
917:	learn: 0.0683807	total: 1.22s	remaining: 109ms
918:	learn: 0.0683725	total: 1.22s	remaining: 108ms
919:	learn: 0.0683077	total: 1.22s	remaining: 106ms
920:	learn: 0.06

[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.424

Ill-conditioned matrix (rcond=2.74251e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75574e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.83786e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78503e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.72177e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.92576e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.70233e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.67385e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78952e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.88052e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.79337e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.82863e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.85086e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.96328e-17): result may not be ac

Ill-conditioned matrix (rcond=2.84087e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75574e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.96231e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.67598e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77607e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78108e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.7712e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78589e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75491e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75902e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.61353e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.94666e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.63092e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.86984e-17): result may not be acc

In [30]:
model_scores = list(zip(model_names, score_rmse))

In [31]:
model_scores

[('CatBoostRegressor', 0.12377861858319061),
 ('XGBRegressor', 0.12039076843055063),
 ('LinearRegression', 0.13634490032529228),
 ('BayesianRidge', 0.1329249668215079),
 ('LGBMRegressor', 0.12229608572161717),
 ('SVR', 0.13458785598565648),
 ('DecisionTreeRegressor', 0.20409527435118138),
 ('RandomForestRegressor', 0.14156761258584682),
 ('GradientBoostingRegressor', 0.12269815792691763),
 ('RidgeRegressor', 0.13144439888498063)]

To stack up all the models above except CatBoost, optimized using linear regressor. For some reason CatBoost wasn't able to run correctly using the StackingCVRegressor model. The decision tree regressor model was also removed since it had a significantly higher score than the other models. 

In [32]:
stackCVreg = StackingCVRegressor(regressors=(xgb_model,lr_model,br_model,lightgbm_model,svr_model,
                                            rfr_model,gbr_model,ridge_model),
                                meta_regressor=lr_model,
                                use_features_in_secondary=True)

In [33]:
print(rmse_cv(stackCVreg,np.array(X),np.array(y)).mean())

[19:35:45] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:35:46] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:35:48] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:35:50] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:35:52] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.55632e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.54244e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.54515e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.69711e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.66968e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.59768e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.99578e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.80743e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.84225e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.53439e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.8079e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.47533e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.23814e-22): result may not be accurate.
Ill-conditioned matrix (rcond=3.42115e-17): result may not be acc

[19:37:33] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=2.74251e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75574e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.83786e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78503e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.72177e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.92576e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.70233e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.67385e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78952e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.88052e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.79337e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.82863e-17): result may not be accurate.


[19:37:59] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:38:01] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:38:03] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:38:05] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:38:06] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.57863e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.83601e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.82515e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.65695e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.53123e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.7892e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.66441e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.67067e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.77235e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.55543e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.76631e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.5709e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.51782e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.40013e-17): result may not be accu

[19:39:49] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=2.85086e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.96328e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.76901e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75104e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.87311e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.89749e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.80568e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.88576e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75584e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.676e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78428e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.007e-17): result may not be accurate.


[19:40:19] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:40:22] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:40:24] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:40:26] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:40:28] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.43511e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.37709e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.36965e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.29905e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.45777e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.27405e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.56548e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.30986e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.4065e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.29854e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.23573e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.42017e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.44968e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.48673e-17): result may not be acc

[19:42:10] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=1.0938e-20): result may not be accurate.
Ill-conditioned matrix (rcond=2.8235e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.86651e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.76315e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.57979e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.69245e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.74664e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.69073e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.62419e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.64391e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.59543e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.73822e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.70161e-17): result may not be accurate.


[19:42:36] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:42:38] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:42:39] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:42:41] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:42:43] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.92554e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.93691e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.60566e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.65313e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.86275e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.64652e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.04134e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.60509e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.80159e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.81528e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.87139e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.62689e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.20976e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.28121e-17): result may not be ac

[19:44:33] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=2.69001e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.83204e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.86763e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.71095e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.76916e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.57489e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.57008e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.73271e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.69243e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.64598e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.6504e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77672e-17): result may not be accurate.


[19:44:59] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:45:01] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:45:03] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:45:04] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:45:06] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.14908e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.3745e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.19808e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.34101e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.41245e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.35271e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.16062e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.41128e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.14065e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.21825e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.4133e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.24973e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.94914e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.54194e-17): result may not be accu

[19:46:52] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=2.88215e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.81276e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78315e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.85624e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.90917e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.80255e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.74166e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.74824e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77438e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.86095e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.65558e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.91264e-17): result may not be accurate.


[19:47:19] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:47:20] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:47:22] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:47:24] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:47:26] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.89974e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.07041e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.27547e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.97889e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.19979e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.88316e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.3079e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.29395e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.06439e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.81216e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.10081e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.0916e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.29298e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.20297e-17): result may not be accu

[19:49:08] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=3.20478e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.89839e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.79208e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.92301e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77398e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77183e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.73265e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.88971e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.72008e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77094e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.7164e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77485e-17): result may not be accurate.


[19:49:35] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:49:36] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:49:38] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:49:40] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:49:42] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.22619e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.32072e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.27135e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.27273e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.27174e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.20461e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.41108e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.27124e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.16643e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.22605e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.36163e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.25634e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.14287e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.16987e-17): result may not be ac

[19:51:35] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=3.06825e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.85881e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.97455e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.85425e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.80265e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.80924e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.83627e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.71275e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.74377e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.81588e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.76782e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.85404e-17): result may not be accurate.


[19:52:02] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:52:04] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:52:06] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:52:07] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:52:09] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.66095e-17): result may not be accurate.
Ill-conditioned matrix (rcond=4.02024e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.53774e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.89925e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.5117e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.56648e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.61487e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.77926e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.83824e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.8713e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.83265e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.68188e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.7928e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.63312e-17): result may not be accur

[19:54:10] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=2.70685e-20): result may not be accurate.
Ill-conditioned matrix (rcond=2.94527e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.98989e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.00767e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.9233e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.96956e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.11943e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.88005e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.09454e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.98506e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.16725e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.80857e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.19926e-17): result may not be accurate.


[19:54:39] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:54:41] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:54:44] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:54:47] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:54:49] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.43953e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.25345e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.29606e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.31162e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.20877e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.21759e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.28636e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.13402e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.43557e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.56011e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.33432e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.3769e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.12858e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.1889e-17): result may not be accu

[19:56:59] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=2.69186e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.80322e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.8599e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.67108e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.84145e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.89748e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.69057e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.72731e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.71201e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.76109e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.61009e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.86054e-17): result may not be accurate.


[19:57:26] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:57:28] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:57:30] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:57:32] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[19:57:34] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.06568e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.3486e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.32721e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.20645e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.09839e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.16599e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.28315e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.26736e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.08226e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.10805e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.26278e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.09233e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.21948e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.48567e-17): result may not be acc

[19:59:42] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=1.29872e-20): result may not be accurate.
Ill-conditioned matrix (rcond=2.71437e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.68408e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.62703e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.65277e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.61664e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.56786e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.54693e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.66594e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77971e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.68317e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.6761e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.61885e-17): result may not be accurate.


[20:00:10] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:00:12] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:00:14] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:00:16] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:00:18] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=3.20767e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.39466e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.31099e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.27949e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.18546e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.33959e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.36148e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.32938e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.55842e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.23557e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.25617e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.35562e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.19093e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.53868e-17): result may not be ac

[20:02:20] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=2.84087e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75574e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.96231e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.67598e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77607e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78108e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.7712e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78589e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75491e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.75902e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.61353e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.94666e-17): result may not be accurate.


[20:02:52] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:02:55] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:02:57] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:03:00] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:03:03] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=4.05144e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.69728e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.73646e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.95019e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.63509e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.7965e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.74447e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.77064e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.77926e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.86224e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.92364e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.85222e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.17503e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.32345e-17): result may not be acc

[20:05:03] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=2.63092e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.86984e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78341e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.74794e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.81388e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.86971e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.76513e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.64043e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.78806e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.6835e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.72277e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.9172e-17): result may not be accurate.


16145.037637199292


To fit all the models in preparation creating an overall blended model. 

In [34]:
cat_model_all_data = cat_model.fit(X,y)
xgb_model_all_data = xgb_model.fit(X,y)
lr_model_all_data = lr_model.fit(X,y)
br_model_all_data = br_model.fit(X,y)
lightgbm_model_all_data = lightgbm_model.fit(X,y)
svr_model_all_data = svr_model.fit(X,y)
rfr_model_all_data = rfr_model.fit(X,y)
gbr_model_all_data = gbr_model.fit(X,y)
ridge_model_all_data = ridge_model.fit(X,y)

0:	learn: 0.3814251	total: 1.93ms	remaining: 1.93s
1:	learn: 0.3645525	total: 4.24ms	remaining: 2.11s
2:	learn: 0.3497168	total: 5.8ms	remaining: 1.93s
3:	learn: 0.3351457	total: 7.32ms	remaining: 1.82s
4:	learn: 0.3242337	total: 9.24ms	remaining: 1.84s
5:	learn: 0.3113050	total: 11.1ms	remaining: 1.84s
6:	learn: 0.3018370	total: 13.1ms	remaining: 1.86s
7:	learn: 0.2915334	total: 14.8ms	remaining: 1.84s
8:	learn: 0.2810088	total: 16.9ms	remaining: 1.86s
9:	learn: 0.2723325	total: 18.7ms	remaining: 1.85s
10:	learn: 0.2640630	total: 20.4ms	remaining: 1.84s
11:	learn: 0.2558824	total: 22.2ms	remaining: 1.83s
12:	learn: 0.2484973	total: 24.9ms	remaining: 1.89s
13:	learn: 0.2411889	total: 26.9ms	remaining: 1.89s
14:	learn: 0.2344371	total: 29.3ms	remaining: 1.93s
15:	learn: 0.2283734	total: 31.7ms	remaining: 1.95s
16:	learn: 0.2230633	total: 33.7ms	remaining: 1.95s
17:	learn: 0.2178149	total: 35.6ms	remaining: 1.94s
18:	learn: 0.2130425	total: 37.3ms	remaining: 1.92s
19:	learn: 0.2093456	to

177:	learn: 0.1100048	total: 342ms	remaining: 1.58s
178:	learn: 0.1099563	total: 344ms	remaining: 1.57s
179:	learn: 0.1097832	total: 346ms	remaining: 1.58s
180:	learn: 0.1097091	total: 348ms	remaining: 1.57s
181:	learn: 0.1095791	total: 349ms	remaining: 1.57s
182:	learn: 0.1094588	total: 351ms	remaining: 1.57s
183:	learn: 0.1093392	total: 353ms	remaining: 1.57s
184:	learn: 0.1092540	total: 355ms	remaining: 1.56s
185:	learn: 0.1090133	total: 357ms	remaining: 1.56s
186:	learn: 0.1090012	total: 359ms	remaining: 1.56s
187:	learn: 0.1089463	total: 361ms	remaining: 1.56s
188:	learn: 0.1087722	total: 362ms	remaining: 1.55s
189:	learn: 0.1086178	total: 364ms	remaining: 1.55s
190:	learn: 0.1083676	total: 366ms	remaining: 1.55s
191:	learn: 0.1082657	total: 368ms	remaining: 1.55s
192:	learn: 0.1081645	total: 369ms	remaining: 1.54s
193:	learn: 0.1081106	total: 371ms	remaining: 1.54s
194:	learn: 0.1080453	total: 373ms	remaining: 1.54s
195:	learn: 0.1079861	total: 378ms	remaining: 1.55s
196:	learn: 

337:	learn: 0.0943748	total: 718ms	remaining: 1.41s
338:	learn: 0.0943007	total: 724ms	remaining: 1.41s
339:	learn: 0.0941440	total: 728ms	remaining: 1.41s
340:	learn: 0.0940837	total: 731ms	remaining: 1.41s
341:	learn: 0.0940792	total: 735ms	remaining: 1.41s
342:	learn: 0.0940384	total: 738ms	remaining: 1.41s
343:	learn: 0.0939544	total: 741ms	remaining: 1.41s
344:	learn: 0.0939325	total: 745ms	remaining: 1.41s
345:	learn: 0.0938274	total: 748ms	remaining: 1.41s
346:	learn: 0.0936654	total: 752ms	remaining: 1.41s
347:	learn: 0.0936465	total: 759ms	remaining: 1.42s
348:	learn: 0.0936282	total: 761ms	remaining: 1.42s
349:	learn: 0.0936247	total: 764ms	remaining: 1.42s
350:	learn: 0.0936046	total: 768ms	remaining: 1.42s
351:	learn: 0.0934034	total: 771ms	remaining: 1.42s
352:	learn: 0.0932520	total: 774ms	remaining: 1.42s
353:	learn: 0.0931643	total: 776ms	remaining: 1.42s
354:	learn: 0.0931274	total: 779ms	remaining: 1.41s
355:	learn: 0.0930235	total: 781ms	remaining: 1.41s
356:	learn: 

581:	learn: 0.0797471	total: 1.28s	remaining: 921ms
582:	learn: 0.0796459	total: 1.28s	remaining: 920ms
583:	learn: 0.0795506	total: 1.29s	remaining: 917ms
584:	learn: 0.0795471	total: 1.29s	remaining: 915ms
585:	learn: 0.0794852	total: 1.29s	remaining: 912ms
586:	learn: 0.0794672	total: 1.29s	remaining: 910ms
587:	learn: 0.0794596	total: 1.29s	remaining: 907ms
588:	learn: 0.0794504	total: 1.3s	remaining: 905ms
589:	learn: 0.0793423	total: 1.3s	remaining: 903ms
590:	learn: 0.0792836	total: 1.3s	remaining: 900ms
591:	learn: 0.0792613	total: 1.3s	remaining: 898ms
592:	learn: 0.0792042	total: 1.3s	remaining: 895ms
593:	learn: 0.0791401	total: 1.31s	remaining: 893ms
594:	learn: 0.0791285	total: 1.31s	remaining: 890ms
595:	learn: 0.0791238	total: 1.31s	remaining: 888ms
596:	learn: 0.0790606	total: 1.31s	remaining: 885ms
597:	learn: 0.0790109	total: 1.31s	remaining: 883ms
598:	learn: 0.0789931	total: 1.31s	remaining: 881ms
599:	learn: 0.0789569	total: 1.32s	remaining: 878ms
600:	learn: 0.078

762:	learn: 0.0723150	total: 1.66s	remaining: 515ms
763:	learn: 0.0722605	total: 1.66s	remaining: 513ms
764:	learn: 0.0722420	total: 1.66s	remaining: 511ms
765:	learn: 0.0721992	total: 1.67s	remaining: 509ms
766:	learn: 0.0721568	total: 1.67s	remaining: 507ms
767:	learn: 0.0721052	total: 1.67s	remaining: 504ms
768:	learn: 0.0720449	total: 1.67s	remaining: 502ms
769:	learn: 0.0720274	total: 1.67s	remaining: 500ms
770:	learn: 0.0720074	total: 1.68s	remaining: 498ms
771:	learn: 0.0719532	total: 1.68s	remaining: 496ms
772:	learn: 0.0719419	total: 1.68s	remaining: 494ms
773:	learn: 0.0719365	total: 1.68s	remaining: 492ms
774:	learn: 0.0719098	total: 1.69s	remaining: 490ms
775:	learn: 0.0718918	total: 1.69s	remaining: 487ms
776:	learn: 0.0718750	total: 1.69s	remaining: 485ms
777:	learn: 0.0718193	total: 1.69s	remaining: 483ms
778:	learn: 0.0718169	total: 1.69s	remaining: 481ms
779:	learn: 0.0717320	total: 1.7s	remaining: 479ms
780:	learn: 0.0716731	total: 1.72s	remaining: 481ms
781:	learn: 0

934:	learn: 0.0665948	total: 2.03s	remaining: 141ms
935:	learn: 0.0665388	total: 2.03s	remaining: 139ms
936:	learn: 0.0665057	total: 2.04s	remaining: 137ms
937:	learn: 0.0664823	total: 2.04s	remaining: 135ms
938:	learn: 0.0664809	total: 2.04s	remaining: 133ms
939:	learn: 0.0664661	total: 2.04s	remaining: 130ms
940:	learn: 0.0664643	total: 2.04s	remaining: 128ms
941:	learn: 0.0664398	total: 2.04s	remaining: 126ms
942:	learn: 0.0664003	total: 2.05s	remaining: 124ms
943:	learn: 0.0663858	total: 2.05s	remaining: 122ms
944:	learn: 0.0663593	total: 2.05s	remaining: 119ms
945:	learn: 0.0662655	total: 2.05s	remaining: 117ms
946:	learn: 0.0662553	total: 2.05s	remaining: 115ms
947:	learn: 0.0662414	total: 2.05s	remaining: 113ms
948:	learn: 0.0662322	total: 2.06s	remaining: 111ms
949:	learn: 0.0661894	total: 2.06s	remaining: 108ms
950:	learn: 0.0661872	total: 2.06s	remaining: 106ms
951:	learn: 0.0660951	total: 2.06s	remaining: 104ms
952:	learn: 0.0660692	total: 2.06s	remaining: 102ms
953:	learn: 

Ill-conditioned matrix (rcond=2.54807e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.58394e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.43973e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.50116e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.54209e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.61996e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.60428e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77327e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.55501e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.42849e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.53396e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.55496e-17): result may not be accurate.


In [35]:
stackCVreg_model = stackCVreg.fit(np.array(X), np.array(y))

[20:06:15] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:06:18] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:06:20] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:06:23] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[20:06:26] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscal

Ill-conditioned matrix (rcond=5.17763e-21): result may not be accurate.
Ill-conditioned matrix (rcond=3.32938e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.35094e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.27908e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.29162e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.41221e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.13627e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.23661e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.23412e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.32594e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.38932e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.34265e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.24077e-17): result may not be accurate.
Ill-conditioned matrix (rcond=3.05556e-17): result may not be ac

[20:08:26] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-0fc7796c793e6356f-1/xgboost/xgboost-ci-windows/src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[LightGBM] [Warning] feature_fraction is set=0.1309662269268009, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1309662269268009
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=1, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=1
[LightGBM] [Warning] bagging_fraction is set=0.4240987934393466, subsample=0.40495582495561083 will be ignored. Current value: bagging_fraction=0.4240987934393466
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4


Ill-conditioned matrix (rcond=2.54807e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.58394e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.43973e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.50116e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.54209e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.61996e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.60428e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.77327e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.55501e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.42849e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.53396e-17): result may not be accurate.
Ill-conditioned matrix (rcond=2.55496e-17): result may not be accurate.


Many of the Kaggle submissions used this type of blending approach. Using 35% for the StackingCVRegressor produced the lowest Kaggle score. Both 30% and 40% produced higher scores. 

In [36]:
# Blend models in order to make the final predictions more robust to overfitting
def blended_predictions(X):
    return ((.1 * ridge_model_all_data.predict(X)) + \
            (.1 * svr_model_all_data.predict(X)) + \
            (.1 * cat_model_all_data.predict(X)) + \
            (.1 * gbr_model_all_data.predict(X)) + \
            (.1 * xgb_model_all_data.predict(X)) + \
            (.1 * lightgbm_model_all_data.predict(X)) + \
            (.05 * rfr_model_all_data.predict(X)) + \
            (0.35 * stackCVreg_model.predict(np.array(X))))

In [37]:
def rmsle(y, y_pred):
    random_state=42
    return np.sqrt(mean_squared_error(y, y_pred))

In [38]:
# Get final precitions from the blended model
blended_score = rmsle(y, blended_predictions(X))
print('RMLSE score on train data:')
print(blended_score)

RMLSE score on train data:
0.08534343999399366


In [39]:
submit = test[['Id']]
submit = submit.reset_index(drop=True)

In [40]:
submit_predict = blended_predictions(test)
submit_predict = np.exp(submit_predict)

In [41]:
submit_predict = np.expm1(blended_predictions(test))

In [42]:
submit['SalePrice'] = submit_predict

In [43]:
submit.to_csv('submit_blended_best_data.csv', index=False)